using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;

namespace THAGBAN_INST.FORM.FRM_LECTUER_MANG.lecteurs
{
    public partial class frm_add_lectuer : DevExpress.XtraEditors.XtraForm
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int lect_id;

        public string lect_name;
        public string lect_desc;
        public string lect_price;
        public int cours_id;
        public string cours_name;


        public frm_add_lectuer()
        {
            InitializeComponent();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void frm_add_job_Load(object sender, EventArgs e)
        {
            get_data();
            if (lect_id != 0)
            {
                TBL_LECTUER tbl = con.TBL_LECTUER.Find(lect_id);
                if (tbl != null)
                {
                    com_cours.SelectedValue =Convert.ToInt32(tbl.LECT_COURS_ID);
                    txt_lect_name.Text = tbl.LECT_NAME;
                    txt_lect_price.Text = tbl.LECT_PRICE.ToString();
                    txt_lect_desc.Text = tbl.LECT_DESC;
                    cours_id= Convert.ToInt32(tbl.LECT_COURS_ID);
                }
               
            }
           
        }
        public void get_data()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
          
                // Bind data to control when loading complete
                com_cours.DataSource = dbContext.TBL_LECT_COURS.ToList();
                com_cours.DisplayMember = "LECT_COURS_NAME";
                com_cours.ValueMember = "LECT_COURS_ID";
           
            com_cours.SelectedValue = Convert.ToInt32(cours_id);
        }
        void clear()
        {
            cours_id = 0;
            lect_id = 0;
            txt_lect_desc.Text = "";
            txt_lect_name.Text = "";
            com_cours.Text = "";
            txt_lect_price.Text = "";


        }
        bool is_empty()
        {
            if (txt_lect_desc.Text != "" && txt_lect_name.Text != "" && com_cours.Text != "")
            {
                return false;
            }
            else
                return true;

        }

        void add_dept()
        {

            tost toast = new tost();
            dialge dialge = new dialge();
            if (is_empty() != true)
            {
                //cheak add or edit 
                try
                {
                    TBL_LECTUER cl = new TBL_LECTUER();
                    cl.LECT_NAME = txt_lect_name.Text;
                    cl.LECT_DESC = txt_lect_desc.Text;
                    cl.LECT_PRICE=Convert.ToInt32(txt_lect_price.Text);
                    cl.LECT_COURS_ID =Convert.ToInt32(com_cours.SelectedValue.ToString());

                    if (lect_id != 0)
                    {
                        //add 
                        cl.LECT_ID = Convert.ToInt32(lect_id);
                        con.TBL_LECTUER.AddOrUpdate(cl);
                        con.SaveChanges();
                        toast.Width = this.Width;

                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.EditNotificationText, THAGBAN_INST.Properties.Resources.edit_32px);
                        notifiction.Show();
                        clear();
                        //MessageBox.Show("تم التعديل بنجاح ");
                    }
                    else
                    {
                        //update 
                        con.TBL_LECTUER.AddOrUpdate(cl);
                        con.SaveChanges();
                        toast.Width = this.Width;
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.AddNotificationText, THAGBAN_INST.Properties.Resources.add_32px);
                        notifiction.Show();
                        clear();

                    }
                }
                catch (Exception ex)
                {

                    //dialge.Width = this.Width;
                    dialge.lbl_mess.Text ="لايمكن اضافه الدوره بنفس الاسم الى الكورس";
                    dialge.Show();
                }
                clear();
            }
            else
            {
               // dialge.Width = this.Width;
                dialge.lbl_mess.Text = "الرجاء ادخال جميع البيانات ";
                dialge.Show();



            }


        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            add_dept();
        }
    }
}