using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.XtraCharts.Native;
using THAGBAN_INST.DATA;

namespace THAGBAN_INST.FORM.FRM_LECTUER_MANG.lecteurs
{
    public partial class lectuer_user : DevExpress.XtraEditors.XtraUserControl
    {
        public int lect_id=0;
        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public lectuer_user()
        {
            InitializeComponent();

            get_data();            
        }
        void get_data()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            THAGBAN_INST.DATA.db_max_instEntities dbContext = new THAGBAN_INST.DATA.db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_LECTUER.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_LECTUER.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        void windowsUIButtonPanel_ButtonClick(object sender, DevExpress.XtraBars.Docking2010.ButtonEventArgs e)
        {
            if (e.Button.Properties.Caption == "Print") gridControl1.ShowRibbonPrintPreview();
        }

        private void windowsUIButtonPanel_Click(object sender, DevExpress.XtraBars.Docking2010.ButtonEventArgs e)
        {
           
        }

        void delete()
        {
            if (lect_id != 0)
            {
                DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                if (res == DialogResult.OK)
                {
                    TBL_LECTUER del_cle = con.TBL_LECTUER.Find(lect_id);
                    // del_doc.DOC_ID = holiday_type_id;

                    con.TBL_LECTUER.Remove(del_cle);
                    con.SaveChanges();
                    adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.DeleteNotificationText, THAGBAN_INST.Properties.Resources.Delete_32px);
                    notifiction.Show();

                }
                get_data();
            }
        }
        private void windowsUIButtonPanel_Click(object sender, EventArgs e)
        {

        }

        private void gridView2_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {

            get_sele();
        }

        void get_sele()
        {
            if (gridView2.RowCount > 0)
            {

                lect_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("LECT_ID").ToString());

            }
        }
        private void btn_save_Click(object sender, EventArgs e)
        {
            frm_add_lectuer frm = new frm_add_lectuer();
            frm.ShowDialog();
            get_data();
        }

        private void btn_edite_Click(object sender, EventArgs e)
        {
            frm_add_lectuer frm = new frm_add_lectuer();
            frm.lect_id = lect_id;
            frm.ShowDialog();
            get_data();
        }

        private void gridView2_SelectionChanged_1(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
            get_sele();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
            get_data();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }
    }
}
