using DevExpress.DataProcessing.InMemoryDataProcessor;
using DevExpress.Office.Utils;
using DevExpress.Utils.Extensions;
using DevExpress.XtraEditors;
using DevExpress.XtraReports.UI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.job;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.lsits;
using THAGBAN_INST.FORM.FRM_LECTUER_MANG.lect_report;

namespace THAGBAN_INST.FORM.FRM_LECTUER_MANG.lect_salary
{
    public partial class frm_add_lect_sal : DevExpress.XtraEditors.XtraForm
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int emp_id = 0;
        int print_id=0;
        public int id = 0;
        public int part_id = 0;
        public int part_paid = 0;
        public int tech_lect_id = 0;
        public int temp_tech_lect_id = 0;
        public int part_rest;
        public int emp_salary;
        public int part_month;
        public string emp_name;
        public int part_year;
        public int total_amount;
        public int total_paid;
        public int lect_id=0;
        public int temp_lect_id = 0;
        int temp_emp_id = 0;

        public DateTime part_date;




        public frm_add_lect_sal()
        {
            InitializeComponent();
           // get_emp();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
         
        }

        public void get_emp()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.

            // Bind data to control when loading complete
            com_emp_name.DataSource = dbContext.TBL_EMPLOYEES.Join(dbContext.TBL_JOB.
            Where(w => w.JOB_NAME == "مدرس"), s => s.TBL_JOB.JOB_ID, w => w.JOB_ID
            , (tech, job) => new
            {
                tech.EMP_NAME,
                tech.EMP_ID,
            }).ToList();
            com_emp_name.DisplayMember = "EMP_NAME";
            com_emp_name.ValueMember = "EMP_ID";
            if (part_id != 0)
            {
                com_emp_name.SelectedValue = temp_emp_id;
            }




        }

      


        void clear()
        {
            emp_salary =0;
            emp_id = 0;
            txt_emp_salary.Text = "";
           
            txt_part_paid.Text ="";
            txt_part_rest.Text = "";
            part_month = 0;
            part_paid = 0;
            part_rest = 0;
            part_year = 0;
            com_emp_name.Text = "";
            part_id = 0;
            total_paid = 0;
            total_amount = 0;
            txt_part_date.Value = DateTime.Now;
            //txt_part_month.Value = DateTime.Now.Month;
            //txt_emp_year.Text = DateTime.Now.Year.ToString();






        }
        bool is_empty()
        {
            if (com_emp_name.Text != "" && txt_part_paid.Text!="" && txt_part_rest.Text!=""&& com_group.Text!=""&& com_lect.Text!="")
            {
                part_paid = Convert.ToInt32(txt_part_paid.Text);
                part_rest = Convert.ToInt32(txt_part_rest.Text);
               // part_year = Convert.ToInt32(txt_emp_year.Text);
               // part_month =Convert.ToInt32(txt_part_month.Value);
                emp_salary = Convert.ToInt32(txt_emp_salary.Text);
                string aa = string.Format("{0:dd-MM-yyyy}", txt_part_date.Value);
                part_date= DateTime.ParseExact(aa, "dd-MM-yyyy", null);
               


                return false;
            }
            else
                return true;

        }

        void add_part_of_salary()
        {

            tost toast = new tost();
            dialge dialge = new dialge();
            if (is_empty() != true)
            {
                //cheak add or edit 
                try
                {
                    TBL_SEND_TECT_LECT cl = new TBL_SEND_TECT_LECT();
                    
                  

                cl.TECH_ID = Convert.ToInt32(com_emp_name.SelectedValue) ;

                    cl.TECH_LECT_ID = Convert.ToInt32(com_group.SelectedValue);

                    cl.LECT_ID = Convert.ToInt32(com_lect.SelectedValue);
                    cl.PAID_UP = Convert.ToInt32(txt_part_paid.Text);
                    cl.REST = Convert.ToInt32(txt_part_rest.Text);
                    cl.INST_ID = THAGBAN_INST.Properties.Settings.Default.inst_id;
                    adl.method method = new adl.method();
                    // string aa = string.Format("{0:dd-MM-yyyy}", );
                    //part_date = DateTime.ParseExact(aa, "dd-MM-yyyy", null);
                    cl.SEND_TECH_DATE = method.convert_date(txt_part_date.Value) ;
                    TBL_OPRATION opration = new TBL_OPRATION();
                    opration.PORATION_AMOUNT = Convert.ToInt32(cl.PAID_UP);
                    opration.PORATION_DATE = cl.SEND_TECH_DATE;
                    opration.OPRATION_TYPE = "سحب";
                    opration.INST_ID = Convert.ToInt32(cl.INST_ID);

                    TBL_INST inst = con.TBL_INST.Find(cl.INST_ID);
                    long total = Convert.ToInt64(inst.INST_TOTAL);
                    total = Convert.ToInt64((total - Convert.ToInt32(opration.PORATION_AMOUNT)));
                    inst.INST_TOTAL = total.ToString();
                    inst.INST_ID = Convert.ToInt32(cl.INST_ID);
                    con.TBL_INST.AddOrUpdate(inst);

                   // MessageBox.Show(inst.INST_TOTAL);
                    if (part_id != 0)
                    {
                        //add 
                        opration.OPRATION_ID = Convert.ToInt32(cl.OPRATION_ID);
                        con.TBL_OPRATION.AddOrUpdate(opration);
                        cl.SEND_STUD_ID = Convert.ToInt32(part_id);
                      


                        con.TBL_SEND_TECT_LECT.AddOrUpdate(cl);
                        con.SaveChanges();
                        print_id = Convert.ToInt32(cl.SEND_STUD_ID);
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.EditNotificationText, THAGBAN_INST.Properties.Resources.edit_32px);
                        notifiction.Show();
                        //clear();
                        //MessageBox.Show("تم التعديل بنجاح ");
                    }
                    else
                    {
                        //update 
                        con.TBL_OPRATION.Add(opration);
                        cl.OPRATION_ID = Convert.ToInt32(opration.OPRATION_ID);
                        con.TBL_SEND_TECT_LECT.AddOrUpdate(cl);
                      
                       
                        con.SaveChanges();
                        print_id = Convert.ToInt32(cl.SEND_STUD_ID);
                       // MessageBox.Show(print_id + "");
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.AddNotificationText, THAGBAN_INST.Properties.Resources.add_32px);
                        notifiction.Show();
                       // clear();

                    }
                   
                }
                catch (Exception ex)
                {


                    //dialge.Width = this.Width;
                    //dialge.lbl_mess.Text ="تاكد من ادخال البيانات بالشكل الصحيح ";
                    //dialge.Show();
                    MessageBox.Show(ex.Message + ex.InnerException.ToString());
                }
              
            }
            else
            {
                dialge.Width = this.Width;
                dialge.lbl_mess.Text = "الرجاء ادخال جميع البيانات ";
                dialge.Show();



            }


        }

        void get_lect()
        {

            com_lect.DataSource = null;
            com_lect.Items.Clear();
            com_lect.Text = "";
            int id = Convert.ToInt32(com_emp_name.SelectedValue);
            var tbl = con.TBL_LECT_TECH_COURS.Where(w =>w.TECHER_ID== id && w.STATE == true)
                .Join(con.TBL_LECTUER, l => l.TBL_LECTUER.LECT_ID, tl => tl.LECT_ID,
                (l, tl) => new
                {

                    l.LECT_ID,
                  
                    tl.LECT_NAME
                   // l.TECHER_ID,

                }).Distinct();


            if (tbl != null)
            {
                com_lect.DataSource = tbl.ToList();
                com_lect.DisplayMember = "LECT_NAME";
                com_lect.ValueMember = "LECT_ID";


                if (part_id != 0)
                {
                    com_lect.SelectedValue = temp_lect_id;
                }
            }
            else
            {
                com_lect.DataSource = null;
                com_lect.Items.Clear();
                com_lect.Text = "";
            }
        }
        void get_group()
        {
       
            try
            {
                com_group.DataSource = null;
                com_group.Items.Clear();
                com_group.Text = "";
                lect_id = Convert.ToInt32(com_lect.SelectedValue);
                emp_id = Convert.ToInt32(com_emp_name.SelectedValue);
                var temp = con.TBL_LECT_TECH_COURS.Where(w => w.LECT_ID == lect_id &&w.TECHER_ID==emp_id).ToList();
                if (temp != null)
                {
                    com_group.DataSource = temp;
                    com_group.DisplayMember = "GROUP_NAME";
                    com_group.ValueMember = "TECH_LECT_ID";
                    if (part_id != 0)
                    {
                        com_group.SelectedValue = temp_tech_lect_id;

                    }


                   
                }
                else
                {
                    dialge di = new dialge();
                    di.lbl_mess.Text= "المدرس لايدرس هذا المستوى";
                    di.Show();
                    com_group.DataSource = null;
                    com_group.Items.Clear();
                    com_group.Text = "";
                }
            }catch(Exception ex) { }


        }
        private void frm_add_emp_Load(object sender, EventArgs e)
        {


           

            if (part_id != 0)
            {
                TBL_SEND_TECT_LECT data_form = con.TBL_SEND_TECT_LECT.Find(part_id);
                temp_emp_id =Convert.ToInt32(data_form.TECH_ID);
                temp_lect_id = Convert.ToInt32(data_form.LECT_ID);
                temp_tech_lect_id = Convert.ToInt32(data_form.TECH_LECT_ID);

                // txt_emp_year.Text = data_form.PART_YEAR.ToString();
                txt_part_date.Value =data_form.SEND_TECH_DATE.Value;
               // txt_part_month.Value = data_form.PART_MONTH ;
                txt_part_paid.Text = data_form.PAID_UP.ToString();
                txt_part_rest.Text = data_form.REST.ToString();

                int temp_oprid = (int)data_form.OPRATION_ID;
                get_inst_data(temp_oprid);

            get_emp();
               
                get_salary();
                //holiday_type_id = Convert.ToInt32(com_holiday_type.SelectedValue.ToString());
                //stud_id= Convert.ToInt32(com_emp_name.SelectedValue.ToString());
               // label1.Text = "emp=" + emp_id.ToString() + "hold";


            }
            else
            {
                get_emp();
                txt_part_date.Value = DateTime.Now;
                //txt_part_month.Value = DateTime.Now.Month;
                //txt_emp_year.Text = DateTime.Now.Year.ToString();
            }

        }
        void get_inst_data(int opri_id)
        {
            int temp_oprid =opri_id ;
            TBL_OPRATION opra = con.TBL_OPRATION.Find(temp_oprid);
            TBL_INST inst = con.TBL_INST.Find(opra.INST_ID);
            long total = Convert.ToInt64(inst.INST_TOTAL);
            total = Convert.ToInt64(total + opra.PORATION_AMOUNT);
            inst.INST_TOTAL = total.ToString();
            MessageBox.Show(inst.INST_TOTAL);
            inst.INST_ID = opra.INST_ID;
            con.TBL_INST.AddOrUpdate(inst);
            con.SaveChanges();

            /// add
            ///  TBL_OPRATION opration = new TBL_OPRATION();
            //opration.PORATION_AMOUNT = Convert.ToInt32(cl.PAID_UP);
            //opration.PORATION_DATE = cl.SEND_TECH_DATE;
            //opration.OPRATION_TYPE = "سحب";
            //opration.INST_ID = Convert.ToInt32(cl.INST_ID);

            //TBL_INST inst = con.TBL_INST.Find(cl.INST_ID);
            //long total = Convert.ToInt64(inst.INST_TOTAL);
            //total = Convert.ToInt64((total - Convert.ToInt32(opration.PORATION_AMOUNT)));
            //inst.INST_TOTAL = total.ToString();
            //inst.INST_ID = Convert.ToInt32(cl.INST_ID);
            //con.TBL_INST.AddOrUpdate(inst);
        }
        private void simpleButton1_Click(object sender, EventArgs e)
        {

            clear();
          

        }

        private void com_dept_SelectedIndexChanged(object sender, EventArgs e)
        {
            
        }

       
       

       

        

       

    private void btn_save_Click(object sender, EventArgs e)
        {
            add_part_of_salary();

        }

        private void com_job_SelectionChangeCommitted(object sender, EventArgs e)
        {
           
        }

        private void btn_emp_list_Click(object sender, EventArgs e)
        {
            emp_list frm = new emp_list();
            frm.ShowDialog(this);
            emp_id = frm.emp_id;
            com_emp_name.Text = frm.emp_name;
        }

        
void get_salary()
        {
            if (emp_id != 0)
            {
                try
                {
                    int id = Convert.ToInt32(com_group.SelectedValue);

                    TBL_LECT_TECH_COURS tem_sal = con.TBL_LECT_TECH_COURS.Where(w => w.LECT_ID == lect_id && w.TECH_LECT_ID == id).FirstOrDefault();
                    if (tem_sal != null)
                    {
                        txt_emp_salary.Text = tem_sal.TECHER_SALARY.ToString();
                    }
                }
                catch(Exception ex)
                {
                  //  MessageBox.Show(ex.Message);
                }
            }

        }
         int Get_piad() {
            int temp=0;
            lect_id=Convert.ToInt32(com_lect.SelectedValue);
            tech_lect_id = Convert.ToInt32(com_group.SelectedValue);
            emp_id = Convert.ToInt32(com_emp_name.SelectedValue);
            var a = con.TBL_SEND_TECT_LECT.
                Where(w => w.TECH_LECT_ID == tech_lect_id && w.LECT_ID == lect_id && w.TECH_ID == emp_id).ToList();
              
            if (a != null)
            {
              total_paid=Convert.ToInt32(a.Sum(w => (int?)w.PAID_UP) ?? 0);

                
                emp_salary =Convert.ToInt32(txt_emp_salary.Text);

                part_rest= (emp_salary - total_paid);
                if (part_rest == 0)
                {

                    txt_part_rest.Text = "تم تسديد كل الميلغ";
                    btn_save.Enabled = false;
                    btn_save_print.Enabled = false;


                }
                else
                {
                    txt_part_rest.Text = part_rest.ToString();
                    //btn_save.Enabled = true;
                    //btn_save_print.Enabled = true;

                }

            }

            return total_paid;

        }
        private void com_emp_name_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (com_emp_name.SelectedItem != null)
            {
                try
                {
                    emp_id = Convert.ToInt32(com_emp_name.SelectedValue);
                    get_lect();
                  ///  get_salary();
                }catch(Exception ex)
                {
                    
                }
            }
        }

        private void txt_part_month_ValueChanged(object sender, EventArgs e)
        {
            get_salary();
        }

        private void txt_emp_year_TextChange(object sender, EventArgs e)
        {
            get_salary();
        }

        private void txt_part_paid_TextChange(object sender, EventArgs e)
        {

        }

        private void com_lect_SelectedValueChanged(object sender, EventArgs e)
        {
            if (com_lect.SelectedValue != null)
            {
                try
                {
                    lect_id=Convert.ToInt32(com_lect.SelectedValue);
                    get_group();
                    Get_piad();
                }catch(Exception ex)
                {

                }
            }
        }

        private void com_group_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (com_group.SelectedValue!=null)

            {
                try
                {
                    get_salary();
                    Get_piad();

                }
                catch(Exception ex) { }
            }
        }

        private void txt_part_paid_TextChanged(object sender, EventArgs e)
        {

            try
            {
                total_amount = Convert.ToInt32(txt_emp_salary.Text) - Get_piad();
                part_paid = Convert.ToInt32(txt_part_paid.Text);
                if (part_paid <= part_rest)
                {
                    txt_part_rest.Text = (total_amount - part_paid).ToString();
                    btn_save.Enabled = true;
                    btn_save_print.Enabled = true;
                }
                else
                {
                    txt_part_rest.Text = "المبلغ اكبرمن المتبقي";
                    btn_save.Enabled = false;
                    btn_save_print.Enabled = false;
                }

            }
            catch(Exception ex)
            {

            }
        }
      

        private void simpleButton2_Click(object sender, EventArgs e)
        {

            add_part_of_salary();
            try
            {
                erp_send_tech report = new erp_send_tech();
                // var temp =con.TBL_SEND_TECT_LECT.Where(w=>w.SEND_STUD_ID==print_id).ToList();
               
                report.DataSource =con.TBL_SEND_TECT_LECT.Where(w=>w.SEND_STUD_ID==print_id).ToList();
                report.DataMember = "";
                report.ShowRibbonPreview();
            }catch(Exception ex) { }



        }
    }
}