using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;
using THAGBAN_INST.FORM.FRM_MANG_STUD.students;

namespace THAGBAN_INST.FORM.FRM_MANG_STUD.stud_foloder
{
    public partial class frm_mang_folo_stud : DevExpress.XtraEditors.XtraUserControl
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        
        public int stud_id = 0;
        public int folder_id = 0;
        public string stud_name;
        public string stud_lname;


        public frm_mang_folo_stud()
        {
            InitializeComponent();
            get_data();


           
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            frm_add_stud_foloder frm = new frm_add_stud_foloder();
            frm.stud_id = 0;
            frm.folder_id = 0;
            frm.ShowDialog();
            get_data();
        }

        public void get_data()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            THAGBAN_INST.DATA.db_max_instEntities dbContext = new THAGBAN_INST.DATA.db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_FOLDER.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_FOLDER.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        void get_sele()
        {
            if (gridView2.SelectedRowsCount > 0)
            {

                
                stud_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("STUD_ID").ToString());
                // holidaytype_id= Convert.ToInt32(gridView2.GetFocusedRowCellValue("DEPT_ID").ToString());
               
                folder_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("FOLDER_ID").ToString());

            }
        }
        private void btn_edite_Click(object sender, EventArgs e)
        {
            frm_add_stud_foloder frm = new frm_add_stud_foloder();
            frm.stud_id =stud_id;
           
           
            frm.folder_id = folder_id;
            frm.btn_save.Text = "تعديل";
            frm.ShowDialog();


            get_data();
        }

        void delete()
        {
            if (stud_id != 0)
            {
                try
                {
                    DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    if (res == DialogResult.OK)
                    {
                        TBL_FOLDER del_cle = con.TBL_FOLDER.Find(folder_id);
                        // del_doc.DOC_ID = holiday_type_id;

                        con.TBL_FOLDER.Remove(del_cle);
                        con.SaveChanges();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.DeleteNotificationText, THAGBAN_INST.Properties.Resources.Delete_32px);
                        notifiction.Show();
                    }
                    get_data();
                }catch (Exception ex) { }
            }
        }
        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            get_sele();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridView2_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
            get_sele();
        }
    }
}
