using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using THAGBAN_INST.DATA;
using THAGBAN_INST.FORM.FRM_MANG_STUD.spical;

namespace THAGBAN_INST.FORM.FRM_MANG_STUD
{
    public partial class frm_mang_spical : DevExpress.XtraEditors.XtraUserControl
    {


        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int spical_id;

        public string spical_name;
        public string spical_desc;
        public string spical_price;
        public int level_id;
        public string levle_name;
        public bool spical_state;
        public DateTime spical_date;

        public frm_mang_spical()
        {
            InitializeComponent();
            get_data();



        }

        public void get_data()
        {


            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            THAGBAN_INST.DATA.db_max_instEntities dbContext = new THAGBAN_INST.DATA.db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_SPECIAL.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_SPECIAL.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        private void btn_save_Click(object sender, EventArgs e)
        {
            frm_add_spical add =new frm_add_spical();
            add.spical_id =0;
            add.ShowDialog();
            get_data();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }

        private void btn_edite_Click(object sender, EventArgs e)
        {
            frm_add_spical frm = new frm_add_spical();
            //frm.holiday_type_name=holiday_type_name;
            frm.level_id = level_id;
            frm.spical_name=spical_name;
            frm.spical_price = spical_price;
            frm.spical_id=spical_id;
            frm.spical_desc=spical_desc;
            frm.spical_date= spical_date;
            frm.spical_state=spical_state;
            frm.btn_save.Text = "تعديل";
            frm.ShowDialog();
            get_data();
        }

        void delete()
        {
            if (spical_id != 0)
            {
                 
                DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                if (res == DialogResult.OK)
                {
                    try
                    {
                        TBL_SPECIAL del_cle = con.TBL_SPECIAL.Find(spical_id);
                        // del_doc.DOC_ID = holiday_type_id;

                        con.TBL_SPECIAL.Remove(del_cle);
                        con.SaveChanges();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.DeleteNotificationText, THAGBAN_INST.Properties.Resources.Delete_32px);
                        notifiction.Show();
                    }
                    catch(Exception e)
                    {

                    }
                }
                get_data();
            }
        }

        void get_sele()
        {
            if (gridView2.SelectedRowsCount > 0)

            {
                spical_name = gridView2.GetFocusedRowCellValue("SPEC_NAME").ToString();
                spical_desc = gridView2.GetFocusedRowCellValue("SPEC_DESC").ToString();
                level_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("LEVEL_ID").ToString());
                spical_price = gridView2.GetFocusedRowCellValue("SPEC_PRICE").ToString();
                spical_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("SPEC_ID").ToString());
                spical_state = bool.Parse(gridView2.GetFocusedRowCellValue("SPEC_STATE").ToString());
                spical_date =DateTime.Parse(gridView2.GetFocusedRowCellValue("SPEC_DATE").ToString());

                // stud_id = gridView2.GetSelectedRows("DEPT_NAME").ToString();

            }
        }

        private void gridView2_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            get_sele();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
            get_data();
        }

        private void gridView2_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            get_sele();
        }

        private void gridView2_Click(object sender, EventArgs e)
        {
            get_sele();
        }

        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            get_sele();
        }
    }
}
