using DevExpress.Office.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraRichEdit.Import.OpenXml;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;

namespace THAGBAN_INST.FORM.FRM_MANG_STUD.spical
{
    public partial class frm_add_spical : DevExpress.XtraEditors.XtraForm
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int spical_id;

        public string spical_name;
        public string spical_desc;
        public string spical_price;
        public int level_id;
        public string level_name;
        public bool spical_state;
        public DateTime spical_date;


        public frm_add_spical()
        {

            InitializeComponent();
           
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void frm_add_job_Load(object sender, EventArgs e)
        {
           
            if (spical_id != 0)
            {
                
                txt_spic_name.Text = spical_name;
                txt_spic_price.Text = spical_price;
                txt_spic_desc.Text = spical_desc;
                if (spical_state == true)
                    rdb_open.Checked = true;
                else
                    rdb_close.Checked = false;
                txt_spiac_date.Value= spical_date;
                //cours_name = con.TBL_LEVLE.Find(spiacla_id).LEVEL_NAME;
                com_level.DataSource = con.TBL_LEVLE.ToList();
                com_level.DisplayMember = "LEVEL_NAME";
                com_level.ValueMember = "LEVEL_ID";
                com_level.SelectedValue =level_id;
               
               // com_level.Text= cours_name;
            }
            else
            {
                get_data();
            }
           
        }
        public void get_data()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_LEVLE.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                com_level.DataSource = dbContext.TBL_LEVLE.Local.ToBindingList();
                com_level.DisplayMember = "LEVEL_NAME";
                com_level.ValueMember = "LEVEL_ID";
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        void clear()
        {
            level_id =0;
            spical_id = 0;
            txt_spic_desc.Text = "";
            txt_spic_name.Text = "";
            com_level.Text = "";
            txt_spic_price.Text = "";
            txt_spiac_date.Value = DateTime.Now;


        }
        bool is_empty()
        {
            if (txt_spic_desc.Text != "" && txt_spic_name.Text != "" && com_level.Text != "" && txt_spic_price.Text!="")
            {
                
                string aa = string.Format("{0:dd-MM-yyyy}", txt_spiac_date.Value);
                spical_date = DateTime.ParseExact(aa, "dd-MM-yyyy", null);
                return false;
            }
            else
                return true;

        }
        string[] years = { "سنه اولى", "سنه ثانيه ", "سنه ثالثه", "سنه رابعه", "سنه خامسه", "سنه سادسه ", "سنه سابعه ", "سنه ثامنه " };

        void add_spical()
        {

            tost toast = new tost();
            dialge dialge = new dialge();
            if (is_empty() != true)
            {
                //cheak add or edit 
                try
                {
                    TBL_SPECIAL cl = new TBL_SPECIAL();
                    cl.SPEC_NAME = txt_spic_name.Text;
                    cl.SPEC_DESC = txt_spic_desc.Text;
                    cl.SPEC_PRICE=Convert.ToInt32(txt_spic_price.Text);
                    cl.LEVEL_ID =Convert.ToInt32(com_level.SelectedValue.ToString());
                    if(rdb_open.Checked)
                    {
                        cl.SPEC_STATE = true;
                    }
                    else
                    cl.SPEC_STATE=false;
                    cl.SPEC_DATE = spical_date;

                    if (spical_id != 0)
                    {
                        //add 
                        add_years(spical_id);
                        cl.SPEC_ID = Convert.ToInt32(spical_id);
                        con.TBL_SPECIAL.AddOrUpdate(cl);
                        con.SaveChanges();
                        toast.Width = this.Width;

                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.EditNotificationText, THAGBAN_INST.Properties.Resources.edit_32px);
                        notifiction.Show();
                        clear();
                        //MessageBox.Show("تم التعديل بنجاح ");
                    }
                    else
                    {
                        spical_id = cl.SPEC_ID;
                        //update 
                        add_years(spical_id);
                        con.TBL_SPECIAL.AddOrUpdate(cl);
                        con.SaveChanges();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.AddNotificationText, THAGBAN_INST.Properties.Resources.add_32px);
                        notifiction.Show();
                        clear();
                    }
                   
                   
                }
                catch (Exception ex)
                {

                    dialge.Width = this.Width;
                    dialge.lbl_mess.Text = ex.Message;
                    dialge.Show();
                }
                clear();
            }
            else
            {
                dialge.Width = this.Width;
                dialge.lbl_mess.Text = "الرجاء ادخال جميع البيانات ";
                dialge.Show();



            }


        }
        void add_years(int spic_id)
        {
            try
            {
                TBL_SPECIAL spec = con.TBL_SPECIAL.Find(spical_id);
                TBL_LEVLE lev = con.TBL_LEVLE.Find(spec.LEVEL_ID);
                int number_of = Convert.ToInt32(lev.N_OF_YEARS);
                MessageBox.Show(spic_id + "   " + number_of.ToString());
                if (spec != null)
                {


                    List<TBL_YEARS> tbl = con.TBL_YEARS.Where(w => w.SPEC_ID == spical_id).ToList();
                    if (tbl.Count > 0)
                    {

                        con.TBL_YEARS.RemoveRange(tbl);
                        con.SaveChanges();


                    }
                    for (int i = 0; i < number_of; i++)
                    {
                        TBL_YEARS yer = new TBL_YEARS();
                        yer.SPEC_ID = spic_id;
                        yer.YEAR_NAME = years[i].ToString();
                        con.TBL_YEARS.Add(yer);
                        con.SaveChanges();
                    }
                }
            }catch(Exception e)
            {

            }
          
        } 
        private void btn_save_Click(object sender, EventArgs e)
        {
            add_spical();
        }

        private void txt_job_note_TextChanged(object sender, EventArgs e)
        {

        }
    }
}