using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;
using THAGBAN_INST.FORM.FRM_LECTUER_MANG.techers;

namespace THAGBAN_INST.FORM.FRM_LECTUER_MANG.techers
{
    public partial class frm_mang_techer : DevExpress.XtraEditors.XtraUserControl
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int job_id = 0;
        public int dept_id = 0;
        public int tech_id = 0;

        public string emp_name;
        public string emp_phone;
        public string emp_address;
        public string emp_gender;
        public string emp_salary;
        public DateTime emp_date;

        public string emp_desc;
        public frm_mang_techer()
        {
            InitializeComponent();
            get_data();
           
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            frm_add_tech frm = new frm_add_tech();
            frm.tech_id = 0;
            frm.ShowDialog();
            get_data();
        }

        public void get_data()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //THAGBAN_INST.DATA.db_max_instEntities dbContext = new THAGBAN_INST.DATA.db_max_instEntities();
            //// Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.TBL_LECT_TECHER.LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    gridControl1.DataSource = dbContext.TBL_LECT_TECHER.Local.ToBindingList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        void get_sele()
        {
            if (gridView2.SelectedRowsCount > 0)
            {

                
               
               // holidaytype_id= Convert.ToInt32(gridView2.GetFocusedRowCellValue("DEPT_ID").ToString());
                tech_id= Convert.ToInt32(gridView2.GetFocusedRowCellValue("TECHER_ID").ToString());

            }
        }
        private void btn_edite_Click(object sender, EventArgs e)
        {
            frm_add_tech frm = new frm_add_tech();
            frm.tech_id =tech_id;
           
            frm.btn_save.Text = "تعديل";
            frm.ShowDialog();
            

           
        }

        void delete()
        {
            if (job_id != 0)
            {
                DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                if (res == DialogResult.OK)
                {
                    //TBL_LECT_TECHER del_cle = con.TBL_LECT_TECHER.Find(tech_id);
                    //// del_doc.DOC_ID = holiday_type_id;

                    //con.TBL_LECT_TECHER.Remove(del_cle);
                    con.SaveChanges();
                    tost not = new tost();
                    not.lbl_mess.Text = "تم الحذف بنجاح ";
                }
                get_data();
            }
        }
        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            get_sele();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }
    }
}
