using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;

namespace THAGBAN_INST.FORM.FRM_EMP_MANEGER
{
    public partial class frm_mang_holiday_type : DevExpress.XtraEditors.XtraUserControl
    {
        public int holiday_type_id=0;
        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        string holiday_type_name;
        string holiday_type_desc;
        string dept_state;
        public frm_mang_holiday_type()
        {
            InitializeComponent();
            get_data();

        }

        void get_data()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_HOLIDAY_TYPE.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_HOLIDAY_TYPE.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        private void simpleButton1_Click(object sender, EventArgs e)
        {

            get_data();
        }

        private void bunifuPanel2_Click(object sender, EventArgs e)
        {

        }


        private void btn_save_Click(object sender, EventArgs e)
        {
            FRM_ADD_holiday_type FRM = new FRM_ADD_holiday_type();
            FRM.holiday_type_id = 0;
           

            FRM.ShowDialog();
            get_data();
        }


        private void btn_edite_Click(object sender, EventArgs e)
        {
            FRM_ADD_holiday_type FRM = new FRM_ADD_holiday_type();
            FRM.holiday_type_id= holiday_type_id;
            FRM.btn_save.Text = "تعديل ";
            FRM.holday_type_dec= holiday_type_desc;
            FRM.holday_type_name = holiday_type_name;
            FRM.ShowDialog();
            get_data();
        }

        private void simpleButton1_Click_1(object sender, EventArgs e)
        {
            get_data();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
            
        }
        void delete()
        {
            if (holiday_type_id != 0)
            {
                try
                {
                    DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    if (res == DialogResult.OK)
                    {
                        TBL_HOLIDAY_TYPE del_cle = con.TBL_HOLIDAY_TYPE.Find(holiday_type_id);
                        // del_doc.DOC_ID = holiday_type_id;

                        con.TBL_HOLIDAY_TYPE.Remove(del_cle);
                        con.SaveChanges();
                        tost not = new tost();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.DeleteNotificationText, THAGBAN_INST.Properties.Resources.Delete_32px);
                        notifiction.Show();
                    }
                    get_data();
                }catch (Exception ex) { }
            }
        }

        void get_sele()
        {
            if (gridView2.SelectedRowsCount > 0)
            {
                holiday_type_desc = gridView2.GetFocusedRowCellValue("HOLIDAY_TYPE_DESC").ToString();
               
               holiday_type_name  = gridView2.GetFocusedRowCellValue("HOLIDAY_TYPE_NAME").ToString();
                holiday_type_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("HOLIDAY_TYPE_ID").ToString());

            }
        }
       

        private void gridView2_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            get_sele();
        }

        private void gridView2_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            get_sele();
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void panelControl1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridView2_FocusedColumnChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedColumnChangedEventArgs e)
        {
            get_sele();
        }

        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            get_sele();
        }

        private void gridView2_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
            get_sele();
        }
    }
}
