using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using THAGBAN_INST.DATA;

namespace THAGBAN_INST.FORM.FRM_EMP_MANEGER.job
{
    public partial class frm_mang_jobs : DevExpress.XtraEditors.XtraUserControl
    {


        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int job_id;

        public string job_name;
        public string job_desc;
        public string job_note;
        public string dept_id;
        public string dept_name;

        public frm_mang_jobs()
        {
            InitializeComponent();
            get_data();


        }

        public void get_data()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_JOB.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_JOB.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        private void btn_save_Click(object sender, EventArgs e)
        {
            frm_add_job add =new frm_add_job();
            add.job_id =0;
            add.ShowDialog();
            get_data();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }

        private void btn_edite_Click(object sender, EventArgs e)
        {
            frm_add_job frm = new frm_add_job();
            //frm.holiday_type_name=holiday_type_name;
            frm.dept_id = dept_id;
            frm.job_name=job_name;
            frm.job_note = job_note;
            frm.job_id=job_id;
            frm.job_desc=job_desc;
            frm.ShowDialog();
            get_data();
        }

        void delete()
        {
            if (job_id != 0)
            {
                try
                {
                    DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    if (res == DialogResult.OK)
                    {
                        TBL_JOB del_cle = con.TBL_JOB.Find(job_id);
                        // del_doc.DOC_ID = holiday_type_id;

                        con.TBL_JOB.Remove(del_cle);
                        con.SaveChanges();
                        tost not = new tost();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.DeleteNotificationText, THAGBAN_INST.Properties.Resources.Delete_32px);
                        notifiction.Show();
                    }
                    get_data();
                }catch (Exception ex) { }
            }
        }

        void get_sele()
        {
            if (gridView2.SelectedRowsCount > 0)

            {
                job_name = gridView2.GetFocusedRowCellValue("JOB_NAME").ToString();
                job_desc = gridView2.GetFocusedRowCellValue("JOB_DESC").ToString();
                dept_id = gridView2.GetFocusedRowCellValue("DEPT_ID").ToString();
                job_note = gridView2.GetFocusedRowCellValue("NOTE").ToString();
                job_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("JOB_ID").ToString());

                // stud_id = gridView2.GetSelectedRows("DEPT_NAME").ToString();

            }
    }

        private void gridView2_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            get_sele();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
            get_data();
        }

        private void gridView2_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            get_sele();
        }

        private void gridView2_Click(object sender, EventArgs e)
        {
            get_sele();
        }

        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            get_sele();
        }
    }
}
