using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;

namespace THAGBAN_INST.FORM.FRM_EMP_MANEGER.lsits
{
    public partial class dept_list : DevExpress.XtraEditors.XtraForm

    {

        public int dept_id;
        public string dept_name;

        public dept_list()
        {
            InitializeComponent();
        }

        private void dept_list_Load(object sender, EventArgs e)
        {
            get_data();
        }

        void get_sele()
        {
            if (gridView2.SelectedRowsCount > 0)
            {
               

                dept_name = gridView2.GetFocusedRowCellValue("DEPT_NAME").ToString();
                dept_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("DEPT_ID").ToString());
               
            
            }
        }
        void get_data()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_DEPT.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_DEPT.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            get_sele();
        }
    }
}