using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;

namespace THAGBAN_INST.FORM.FRM_EMP_MANEGER.lsits
{
    public partial class holiday_type_list : DevExpress.XtraEditors.XtraForm

    {

        public int holiday_type_id;
        public string holiday_type_name;

        public holiday_type_list()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_HOLIDAY_TYPE.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.TBL_HOLIDAY_TYPE.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void dept_list_Load(object sender, EventArgs e)
        {
        }

        void get_sele()
        {
            if (gridView2.SelectedRowsCount > 0)
            {

                holiday_type_name = gridView2.GetFocusedRowCellValue("HOLIDAY_TYPE_NAME").ToString();
                holiday_type_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("HOLIDAY_TYPE_ID").ToString());

            }
        }
       
        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            get_sele();
        }
    }
}