//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SEND_TECT_LECT
    {
        public int SEND_STUD_ID { get; set; }
        public Nullable<int> TECH_ID { get; set; }
        public Nullable<int> TECH_LECT_ID { get; set; }
        public Nullable<int> PAID_UP { get; set; }
        public Nullable<int> LECT_ID { get; set; }
        public Nullable<int> REST { get; set; }
        public Nullable<System.DateTime> SEND_TECH_DATE { get; set; }
        public Nullable<int> INST_ID { get; set; }
        public Nullable<int> OPRATION_ID { get; set; }
    
        public virtual TBL_EMPLOYEES TBL_EMPLOYEES { get; set; }
        public virtual TBL_INST TBL_INST { get; set; }
        public virtual TBL_LECT_TECH_COURS TBL_LECT_TECH_COURS { get; set; }
        public virtual TBL_LECTUER TBL_LECTUER { get; set; }
        public virtual TBL_OPRATION TBL_OPRATION { get; set; }
    }
}
