//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LEVLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LEVLE()
        {
            this.TBL_SPECIAL = new HashSet<TBL_SPECIAL>();
        }
    
        public int LEVEL_ID { get; set; }
        public string LEVEL_NAME { get; set; }
        public string LEVEL_DESC { get; set; }
        public Nullable<bool> LEVEL_STATE { get; set; }
        public int INST_ID { get; set; }
        public Nullable<int> N_OF_YEARS { get; set; }
    
        public virtual TBL_INST TBL_INST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SPECIAL> TBL_SPECIAL { get; set; }
    }
}
