//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LECT_MATRIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LECT_MATRIAL()
        {
            this.TBL_LECT_MARK = new HashSet<TBL_LECT_MARK>();
        }
    
        public int MATRIAL_LECT_ID { get; set; }
        public string MATRIAL_LECT_NAME { get; set; }
        public Nullable<int> LECT_ID { get; set; }
        public Nullable<int> LECT_COURS_ID { get; set; }
    
        public virtual TBL_LECT_COURS TBL_LECT_COURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LECT_MARK> TBL_LECT_MARK { get; set; }
        public virtual TBL_LECTUER TBL_LECTUER { get; set; }
    }
}
