//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SPECIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SPECIAL()
        {
            this.TBL_MARKS = new HashSet<TBL_MARKS>();
            this.TBL_SPE_COURS = new HashSet<TBL_SPE_COURS>();
            this.TBL_STUD_SPEC = new HashSet<TBL_STUD_SPEC>();
            this.TBL_TERMS = new HashSet<TBL_TERMS>();
            this.TBL_YEARS = new HashSet<TBL_YEARS>();
        }
    
        public int SPEC_ID { get; set; }
        public string SPEC_NAME { get; set; }
        public string SPEC_DESC { get; set; }
        public double SPEC_PRICE { get; set; }
        public bool SPEC_STATE { get; set; }
        public Nullable<int> LEVEL_ID { get; set; }
        public Nullable<System.DateTime> SPEC_DATE { get; set; }
    
        public virtual TBL_LEVLE TBL_LEVLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MARKS> TBL_MARKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SPE_COURS> TBL_SPE_COURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STUD_SPEC> TBL_STUD_SPEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TERMS> TBL_TERMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_YEARS> TBL_YEARS { get; set; }
    }
}
