//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OPRATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_OPRATION()
        {
            this.TBL_PART_SALARY = new HashSet<TBL_PART_SALARY>();
            this.TBL_SEND_STUD_LECT = new HashSet<TBL_SEND_STUD_LECT>();
            this.TBL_SEND_TECT_LECT = new HashSet<TBL_SEND_TECT_LECT>();
        }
    
        public int OPRATION_ID { get; set; }
        public string OPRATION_TYPE { get; set; }
        public Nullable<int> PORATION_AMOUNT { get; set; }
        public Nullable<System.DateTime> PORATION_DATE { get; set; }
        public int INST_ID { get; set; }
    
        public virtual TBL_INST TBL_INST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PART_SALARY> TBL_PART_SALARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEND_STUD_LECT> TBL_SEND_STUD_LECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEND_TECT_LECT> TBL_SEND_TECT_LECT { get; set; }
    }
}
