//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LECTUER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_LECTUER()
        {
            this.TBL_LECT_MARK = new HashSet<TBL_LECT_MARK>();
            this.TBL_LECT_MATRIAL = new HashSet<TBL_LECT_MATRIAL>();
            this.TBL_LECT_TECH_COURS = new HashSet<TBL_LECT_TECH_COURS>();
            this.TBL_SEND_STUD_LECT = new HashSet<TBL_SEND_STUD_LECT>();
            this.TBL_SEND_TECT_LECT = new HashSet<TBL_SEND_TECT_LECT>();
            this.TBL_STUD_LECT = new HashSet<TBL_STUD_LECT>();
        }
    
        public int LECT_ID { get; set; }
        public string LECT_NAME { get; set; }
        public string LECT_DESC { get; set; }
        public Nullable<int> LECT_PRICE { get; set; }
        public Nullable<int> LECT_COURS_ID { get; set; }
    
        public virtual TBL_LECT_COURS TBL_LECT_COURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LECT_MARK> TBL_LECT_MARK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LECT_MATRIAL> TBL_LECT_MATRIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LECT_TECH_COURS> TBL_LECT_TECH_COURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEND_STUD_LECT> TBL_SEND_STUD_LECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEND_TECT_LECT> TBL_SEND_TECT_LECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STUD_LECT> TBL_STUD_LECT { get; set; }
    }
}
