//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PART_SALARY
    {
        public int PART_ID { get; set; }
        public Nullable<int> PAID_REST { get; set; }
        public int PART_PAID { get; set; }
        public int PART_MONTH { get; set; }
        public int PART_YEAR { get; set; }
        public int EMP_ID { get; set; }
        public System.DateTime SLAARY_DATE { get; set; }
        public Nullable<int> OPRATION_ID { get; set; }
    
        public virtual TBL_EMPLOYEES TBL_EMPLOYEES { get; set; }
        public virtual TBL_OPRATION TBL_OPRATION { get; set; }
    }
}
