//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLOYEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_EMPLOYEES()
        {
            this.TBL_ATTENDS = new HashSet<TBL_ATTENDS>();
            this.TBL_HOLIDAYS = new HashSet<TBL_HOLIDAYS>();
            this.TBL_LECT_TECH_COURS = new HashSet<TBL_LECT_TECH_COURS>();
            this.TBL_PART_SALARY = new HashSet<TBL_PART_SALARY>();
            this.TBL_SALARY = new HashSet<TBL_SALARY>();
            this.TBL_SEND_TECT_LECT = new HashSet<TBL_SEND_TECT_LECT>();
            this.TBL_USERS = new HashSet<TBL_USERS>();
        }
    
        public int EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_GENDER { get; set; }
        public string EMP_PHONE { get; set; }
        public double EMP_SALARY { get; set; }
        public string EMP_ADDRESS { get; set; }
        public System.DateTime EMP_DATE { get; set; }
        public string EMP_DESC { get; set; }
        public Nullable<int> JOB_ID { get; set; }
        public Nullable<bool> STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ATTENDS> TBL_ATTENDS { get; set; }
        public virtual TBL_JOB TBL_JOB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HOLIDAYS> TBL_HOLIDAYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LECT_TECH_COURS> TBL_LECT_TECH_COURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PART_SALARY> TBL_PART_SALARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SALARY> TBL_SALARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEND_TECT_LECT> TBL_SEND_TECT_LECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_USERS> TBL_USERS { get; set; }
    }
}
