//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ACTIVE_SYSTEM
    {
        public string Mack_address { get; set; }
        public string Key { get; set; }
        public Nullable<System.DateTime> Added_date { get; set; }
        public Nullable<bool> FLUL_ACTIVE { get; set; }
        public string FULT_ACTIVE_KEY { get; set; }
        public Nullable<bool> SUB_ACTIVE { get; set; }
    }
}
