//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FOLDER
    {
        public int FOLDER_ID { get; set; }
        public Nullable<bool> CRTIFIVATE_CHEAK { get; set; }
        public byte[] CRTIFIVATE_IMG { get; set; }
        public Nullable<bool> CART_CHEAK { get; set; }
        public byte[] CART_IMG { get; set; }
        public Nullable<bool> STUD_IMG_CHEAK { get; set; }
        public byte[] STUD_IMG { get; set; }
        public Nullable<bool> INST_NOTE_CHEAK { get; set; }
        public byte[] INST_NOTE_IMG { get; set; }
        public Nullable<int> STUD_ID { get; set; }
    
        public virtual TBL_STUDENTS TBL_STUDENTS { get; set; }
    }
}
