//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STUDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_STUDENTS()
        {
            this.TBL_FOLDER = new HashSet<TBL_FOLDER>();
            this.TBL_LECT_MARK = new HashSet<TBL_LECT_MARK>();
            this.TBL_MARKS = new HashSet<TBL_MARKS>();
            this.TBL_SEND_STUD_LECT = new HashSet<TBL_SEND_STUD_LECT>();
            this.TBL_STUD_LECT = new HashSet<TBL_STUD_LECT>();
            this.TBL_STUD_SPEC = new HashSet<TBL_STUD_SPEC>();
            this.TBL_STUD_STUDY_COURS = new HashSet<TBL_STUD_STUDY_COURS>();
        }
    
        public int STUD_ID { get; set; }
        public string STUD_NAME { get; set; }
        public string STUD_LNAME { get; set; }
        public string STUD_GENDER { get; set; }
        public string STUD_ADDRESS { get; set; }
        public string STUD_PHONE { get; set; }
        public bool STUD_STATE { get; set; }
        public System.DateTime STUD_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FOLDER> TBL_FOLDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LECT_MARK> TBL_LECT_MARK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MARKS> TBL_MARKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SEND_STUD_LECT> TBL_SEND_STUD_LECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STUD_LECT> TBL_STUD_LECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STUD_SPEC> TBL_STUD_SPEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_STUD_STUDY_COURS> TBL_STUD_STUDY_COURS { get; set; }
    }
}
