//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROULLS_LECTUER
    {
        public int USER_ID { get; set; }
        public Nullable<bool> ch_activ { get; set; }
        public Nullable<bool> ch_admin { get; set; }
        public Nullable<bool> ch_apu { get; set; }
        public Nullable<bool> ch_attend { get; set; }
        public Nullable<bool> ch_cours_lect { get; set; }
        public Nullable<bool> ch_dept { get; set; }
        public Nullable<bool> ch_emp { get; set; }
        public Nullable<bool> ch_job { get; set; }
        public Nullable<bool> ch_lect { get; set; }
        public Nullable<bool> ch_lect_stud { get; set; }
        public Nullable<bool> ch_main { get; set; }
        public Nullable<bool> ch_mark { get; set; }
        public Nullable<bool> ch_matrila { get; set; }
        public Nullable<bool> ch_report { get; set; }
        public Nullable<bool> ch_sala { get; set; }
        public Nullable<bool> ch_send_stud { get; set; }
        public Nullable<bool> ch_send_tech { get; set; }
        public Nullable<bool> ch_sett { get; set; }
        public Nullable<bool> ch_stud { get; set; }
        public Nullable<bool> ch_tech_lec { get; set; }
    
        public virtual TBL_USERS TBL_USERS { get; set; }
    }
}
