using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.employees;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.users;

namespace THAGBAN_INST.FORM.FRM_EMP_MANEGER
{
    public partial class frm_mang_emp : DevExpress.XtraEditors.XtraUserControl
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int job_id = 0;
        public int dept_id = 0;
        public int emp_id = 0;

        public string emp_name;
        public string emp_phone;
        public string emp_address;
        public string emp_gender;
        public string emp_salary;
        public DateTime emp_date;

        public string emp_desc;
        public frm_mang_emp()
        {
            InitializeComponent();
            get_data();
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            frm_add_emp frm = new frm_add_emp();
            frm.emp_id = 0;
            frm.ShowDialog();
            get_data();
        }

        public void get_data()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_EMPLOYEES.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_EMPLOYEES.Local.ToBindingList().Where(w=>w.STATE==true);
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        void get_sele()
        {
            if (gridView2.SelectedRowsCount > 0)
            {

                
                emp_name = gridView2.GetFocusedRowCellValue("EMP_NAME").ToString();
                emp_phone = gridView2.GetFocusedRowCellValue("EMP_PHONE").ToString();
                string aa = gridView2.GetFocusedRowCellValue("EMP_DATE").ToString();
                emp_date = DateTime.Parse(aa);
                emp_desc = gridView2.GetFocusedRowCellValue("EMP_DESC").ToString();
                emp_address = gridView2.GetFocusedRowCellValue("EMP_ADDRESS").ToString();
                emp_gender = gridView2.GetFocusedRowCellValue("EMP_GENDER").ToString();
                emp_salary = gridView2.GetFocusedRowCellValue("EMP_SALARY").ToString();
                emp_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("EMP_ID").ToString());
               // holidaytype_id= Convert.ToInt32(gridView2.GetFocusedRowCellValue("DEPT_ID").ToString());
                job_id= Convert.ToInt32(gridView2.GetFocusedRowCellValue("JOB_ID").ToString());

            }
        }
        private void btn_edite_Click(object sender, EventArgs e)
        {
            frm_add_emp frm = new frm_add_emp();
            frm.emp_id =emp_id;
            frm.emp_address =emp_address;
            frm.emp_gender =emp_gender;
            frm.emp_date =emp_date;
            frm.emp_desc =emp_desc;
            frm.emp_name =emp_name;
            frm.emp_phone =emp_phone;
            frm.emp_salary=emp_salary;
            dept_id= (int)con.TBL_JOB.Find(job_id).DEPT_ID;
            frm.dept_name =con.TBL_DEPT.Find(dept_id).DEPT_NAME;
            frm.job_name = con.TBL_JOB.Find(job_id).JOB_NAME;

            frm.job_id =job_id;
            frm.btn_save.Text = "تعديل";
            frm.ShowDialog();
            

           
        }

        void delete()
        {
            if (job_id != 0)
            {
                try
                {
                    DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    if (res == DialogResult.OK)
                    {
                        TBL_EMPLOYEES del_cle = con.TBL_EMPLOYEES.Find(emp_id);
                        // del_doc.DOC_ID = holiday_type_id;

                        con.TBL_EMPLOYEES.Remove(del_cle);
                        con.SaveChanges();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.DeleteNotificationText, THAGBAN_INST.Properties.Resources.Delete_32px);
                        notifiction.Show();
                    }
                    get_data();
                }catch(Exception ex) { }
            }
        }
        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            get_sele();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            get_sele();
                frm_add_users frm = new frm_add_users();
                frm.emp_id= emp_id;
                frm.ShowDialog();
            
        }

        private void gridView2_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
            get_sele();
        }
    }
}
