using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.employees;
using THAGBAN_INST.DATA;
using THAGBAN_INST.reports.emp_reports;
using DevExpress.XtraReports.UI;
using THAGBAN_INST.FORM.FRM_LECTUER_MANG.lect_report;
using THAGBAN_INST.adl;

namespace THAGBAN_INST.FORM.FRM_LECTUER_MANG.reports
{
    public partial class frm_mange_report : DevExpress.XtraEditors.XtraUserControl
    {
        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int emp_id = 0;
        public int part_id = 0;
        public int part_paid = 0;
        public int part_rest;
        public int emp_salary;
        public int part_month;
        public string emp_name;
        public int part_year;
        public int total_amount;
        public int total_paid;


        public DateTime part_date;
        private int tech_lect_id;
        private int lect_id;
        private int stud_id;

        public frm_mange_report()
        {
            InitializeComponent();


            get_data();

           
        }
        void get_data()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            THAGBAN_INST.DATA.db_max_instEntities dbContext = new THAGBAN_INST.DATA.db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_SEND_STUD_LECT.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_SEND_STUD_LECT.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        void print_report()
        {
            reort_send_lect _Lect = new reort_send_lect();

            if (com_lect.Enabled == true && com_group.Enabled == false && com_stud.Enabled == false)
            {
                if (com_lect.SelectedValue != null)
                    lect_id = Convert.ToInt32(com_lect.SelectedValue);
                var temp_lec = con.TBL_SEND_STUD_LECT.Where(w => w.LECT_ID == lect_id).ToList();
                // _Lect.DataSource=con.TBL_SEND_STUD_LECT.Where(w=>w.id)
                if (temp_lec.Count > 0)
                {
                    gridControl1.DataSource = temp_lec.ToList();
                    //_Lect.DataSource = gridControl1.DataSource;
                    //_Lect.ShowPreview();
                    //_Lect.ShowRibbonPreview();
                }
                else
                {
                    NotifictionUser notif = new NotifictionUser("    لايوجد طلاب مسددين  في هذه الدوره ", THAGBAN_INST.Properties.Resources.icons8_Notification_128px);
                    notif.StartPosition = FormStartPosition.CenterScreen;
                    notif.Show();
                }
            }


            else if (com_lect.Enabled == true && com_group.Enabled == true && com_stud.Enabled == false)
            {
                if (com_group.SelectedValue != null)
                    tech_lect_id = Convert.ToInt32(com_group.SelectedValue);
                var temp_tech = con.TBL_SEND_STUD_LECT.Where(w => w.LECT_ID == lect_id && w.TECH_LECT_ID == tech_lect_id).ToList();
                // _Lect.DataSource=con.TBL_SEND_STUD_LECT.Where(w=>w.id)
                if (temp_tech.Count > 0)
                {
                    gridControl1.DataSource = temp_tech;
                    //_Lect.ShowRibbonPreview();
                }
                else
                {
                    NotifictionUser notif = new NotifictionUser("    لايوجد طلاب مسددين  في هذه الدوره ", THAGBAN_INST.Properties.Resources.icons8_Notification_128px);
                    notif.StartPosition = FormStartPosition.CenterScreen;
                    notif.Show();
                }
            }

            else if (com_lect.Enabled == true && com_group.Enabled == true && com_stud.Enabled == true)
            {
                if (com_group.SelectedValue != null)
                    tech_lect_id = Convert.ToInt32(com_group.SelectedValue);
                stud_id = Convert.ToInt32(com_stud.SelectedValue);
                var temp = con.TBL_SEND_STUD_LECT.Where(w => w.LECT_ID == lect_id && w.TECH_LECT_ID == tech_lect_id && w.STUD_ID == stud_id).ToList();
                // _Lect.DataSource=con.TBL_SEND_STUD_LECT.Where(w=>w.id)
                if (temp.Count > 0)
                {
                    gridControl1.DataSource = temp;
                    //_Lect.ShowRibbonPreview();
                }
                else
                {
                    NotifictionUser notif = new NotifictionUser("    لايوجد طلاب مسددين  في هذه الدوره ", THAGBAN_INST.Properties.Resources.icons8_Notification_128px);
                    notif.StartPosition = FormStartPosition.CenterScreen;
                    notif.Show();
                }
            }

            else if (com_lect.Enabled == true && com_group.Enabled == false && com_stud.Enabled == true)
            {
                if (com_group.SelectedValue != null)
                    tech_lect_id = Convert.ToInt32(com_group.SelectedValue);
                stud_id = Convert.ToInt32(com_stud.SelectedValue);
                var temp = con.TBL_SEND_STUD_LECT.Where(w => w.LECT_ID == lect_id && w.STUD_ID == stud_id).ToList();
                // _Lect.DataSource=con.TBL_SEND_STUD_LECT.Where(w=>w.id)
                if (temp.Count > 0)
                {
                    gridControl1.DataSource = temp;
                    //_Lect.ShowRibbonPreview();
                }
                else
                {
                    NotifictionUser notif = new NotifictionUser("    لايوجد طلاب مسددين  في هذه الدوره ", THAGBAN_INST.Properties.Resources.icons8_Notification_128px);
                    notif.StartPosition = FormStartPosition.CenterScreen;
                    notif.Show();
                }
            }

            else if (com_stud.Enabled == true && com_lect.Enabled == false && com_group.Enabled == false)
            {
                if (com_stud.SelectedValue != null)
                    stud_id = Convert.ToInt32(com_stud.SelectedValue);
                var temp1 = con.TBL_SEND_STUD_LECT.Where(w => w.STUD_ID == stud_id).ToList();
                if (temp1.Count > 0)
                {
                    gridControl1.DataSource=temp1;
                    //_Lect.DataSource = temp1;
                    //_Lect.ShowPreview();
                    // _Lect.ShowRibbonPreview();
                }
                else
                {
                    NotifictionUser notif = new NotifictionUser(" الطالب  غير مسدد    ", THAGBAN_INST.Properties.Resources.icons8_Notification_128px);
                    notif.StartPosition = FormStartPosition.CenterScreen;
                    notif.Show();
                }
            }

            else if (com_stud.Enabled == true && com_lect.Enabled == false && com_group.Enabled == true)
            {
                if (com_stud.SelectedValue != null)
                    stud_id = Convert.ToInt32(com_stud.SelectedValue);
                var temp1 = con.TBL_SEND_STUD_LECT.Where(w => w.STUD_ID == stud_id && w.TECH_LECT_ID == tech_lect_id).ToList();
                if (temp1.Count > 0)
                {
                    gridControl1.DataSource = temp1;
                    // _Lect.ShowRibbonPreview();
                }
                else
                {
                    NotifictionUser notif = new NotifictionUser(" الطالب  غير مسدد    ", THAGBAN_INST.Properties.Resources.icons8_Notification_128px);
                    notif.StartPosition = FormStartPosition.CenterScreen;
                    notif.Show();
                }
            }

            else
            {

                //_Lect.DataSource = con.TBL_SEND_STUD_LECT.ToList();

                // _Lect.ShowPreview();
                var temp1 = con.TBL_SEND_STUD_LECT.ToList();
                if (temp1.Count > 0)
                {
                    gridControl1.DataSource = temp1.ToList();
                    // _Lect.ShowPreview();

                    // _Lect.ShowRibbonPreview();
                }
                else
                {
                    NotifictionUser notif = new NotifictionUser(" لايوجد طلاب مسجيلين في الدورات ", THAGBAN_INST.Properties.Resources.icons8_Notification_128px);
                    notif.StartPosition = FormStartPosition.CenterScreen;
                    notif.Show();
                }
                // _Lect.DataSource=con.TBL_SEND_STUD_LECT.Where(w=>w.id)

            }



        }
        public void get_lect()
        {
            var tbl = con.TBL_LECT_TECH_COURS.Where(w => w.STATE == true)
                .Join(con.TBL_LECTUER, l => l.TBL_LECTUER.LECT_ID, tl => tl.LECT_ID,
                (l, tl) => new
                {

                    l.LECT_ID,

                    tl.LECT_NAME,

                }).Distinct();


            if (tbl != null)
            {
                com_lect.DataSource = tbl.ToList();
                com_lect.DisplayMember = "LECT_NAME";
                com_lect.ValueMember = "LECT_ID";
              //  lbl_lect_tech.Text = tbl.Count().ToString();
                get_group();


            }
            else
            {
                com_lect.DataSource = null;
                com_lect.Items.Clear();
                com_lect.Text = "";
            }
        }
        public void get_group()
        {
            try
            {

                lect_id = Convert.ToInt32(com_lect.SelectedValue);
                var temp = con.TBL_LECT_TECH_COURS.Where(w => w.LECT_ID == lect_id).Distinct().ToList();
                if (temp != null)
                {
                    com_group.DataSource = temp;
                    com_group.DisplayMember = "GROUP_NAME";
                    com_group.ValueMember = "TECH_LECT_ID";


                }
                else
                {
                    com_group.DataSource = null;
                    com_group.Items.Clear();
                    com_group.Text = "";
                }
            }
            catch (Exception ex) { }


        }
        public void get_stud()
        {


            try
            {
                tech_lect_id = Convert.ToInt32(com_group.SelectedValue);
                lect_id = Convert.ToInt32(com_lect.SelectedValue);
                com_stud.DataSource = con.TBL_STUD_LECT.Where(w => w.LECT_TECH_ID
                == tech_lect_id && w.LECT_ID == lect_id).Join(
                    con.TBL_STUDENTS, sl => sl.STUD_ID, stud => stud.STUD_ID,
                    (stud, sl) => new
                    {
                        sl.STUD_NAME,
                        sl.STUD_LNAME,
                        stud.STUD_ID
                    }).Distinct().ToList();

                com_stud.DisplayMember = "STUD_NAME";
                com_stud.ValueMember = "STUD_ID";
            }
            catch (Exception ex) { }


        }
        private void gridView2_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
           
        }
       

        private void btn_edite_Click(object sender, EventArgs e)
        {
            //frm_add_lect_send_stud frm= new frm_add_lect_send_stud();
            //get_sel();
            //frm.part_id = part_id;
            //frm.btn_save.Text = "تعديل";
            //frm.ShowDialog();
            //get_data();
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            //frm_add_lect_send_stud frm = new frm_add_lect_send_stud();
            //frm.part_id = 0;
            //frm.ShowDialog();
            //get_data();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            
        }
      

        private void gridView2_SelectionChanged_1(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
           

        }

        void cheack_change()
        {

            if (ch_lect.Checked)
            {
                groupBox1.Enabled = true;
                com_lect.Enabled = true;
            }
            else
            {
                com_lect.Enabled = false;
            }
            if (ch_grou.Checked)
            {
                com_group.Enabled = true;

            }
            else
            {
                //groupBox1.Enabled = false;
                //groupBox1.Visible = false;
                com_group.Enabled = false;
            }
            if (ch_stud.Checked)
            {
                com_stud.Enabled = true;
            }
            else
            {
                com_stud.Enabled = false;
            }
            
        }
        private void simpleButton2_Click(object sender, EventArgs e)
        {
          //  gridControl1.ShowRibbonPrintPreview();
        }

        private void simpleButton2_Click_1(object sender, EventArgs e)
        {

        }

        private void ch_lect_CheckedChanged(object sender, EventArgs e)
        {
            cheack_change();
            get_lect();
        }

        private void ch_grou_CheckedChanged(object sender, EventArgs e)
        {
            cheack_change();
            get_group();
        }

        private void ch_stud_CheckedChanged(object sender, EventArgs e)
        {
            cheack_change();
            get_stud();
        }

        private void com_lect_SelectionChangeCommitted(object sender, EventArgs e)
        {
            try
            {
                if(com_lect.SelectedValue!=null)
                {
                    lect_id = Convert.ToInt32(com_lect.SelectedValue);
                    get_group();
                    print_report();
                }
            }catch (Exception ex) { }
        }

        private void com_group_SelectionChangeCommitted(object sender, EventArgs e)
        {
            try
            {
                if (com_group.SelectedValue != null)
                {
                    tech_lect_id = Convert.ToInt32(com_group.SelectedValue);
                    get_stud();
                    print_report();
                }
            }
            catch (Exception ex) { }
        }

        private void com_stud_SelectionChangeCommitted(object sender, EventArgs e)
        {
            try
            {
                if (com_stud.SelectedValue != null)
                {
                    stud_id = Convert.ToInt32(com_stud.SelectedValue);
                    print_report();
                }
            }
            catch (Exception ex) { }
        }

        private void simpleButton2_Click_2(object sender, EventArgs e)
        {
            //  gridControl1.ShowRibbonPrintPreview();
            reort_send_lect rpt = new reort_send_lect();
            rpt.DataSource = gridControl1.DataSource;
            report_send_stud ro = new report_send_stud();

            ro.DataSource = gridControl1.DataSource;
            
            rpt.ShowPreview();
        }

        private void panel4_Paint(object sender, PaintEventArgs e)
        {

        }

        private void frm_mange_report_Load(object sender, EventArgs e)
        {
            cheack_change();
        }
    }
}
