using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace THAGBAN_INST.FORM.FRM_SYSTEM
{
    public partial class AnalyticsPage : DevExpress.XtraEditors.XtraUserControl
    {
        double currValue;
        public AnalyticsPage()
        {
            InitializeComponent();
            LoadData();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
           // EPS.DBEPSEntities dbContext = new EPS.DBEPSEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
    //        dbContext.TB_Sell.LoadAsync().ContinueWith(loadTask =>
    //        {
    //// Bind data to control when loading complete
    //chartControl1.DataSource = dbContext.TB_Sell.Local.ToBindingList();
    //        }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }




        private void LoadData()
        {
            LoadDataSupplier();
            LoadDataCustomer();
            LoadDataSell();
            Loadbenfit();
            LoadDataBuy();
        }

        private void LoadDataSupplier()
        {
            try
            {
                //var curr1 = Properties.Settings.Default.PrimaryCurrName;
                //var curr2 = Properties.Settings.Default.SecondryCurrName;
                //DBEPSEntities db = new DBEPSEntities();
                //lb_supplier1.Text = db.TB_Suppliers.Select(x => x.SupplierBalance).ToArray().Sum().ToString() + "   " + curr1;
                //lb_supplier2.Text = db.TB_Suppliers.Select(x => x.SupplierBalancePrim).ToArray().Sum().ToString() + "   " + curr2;

            }
            catch { }
        }

        private void LoadDataCustomer()
        {
            try
            {
                //var curr1 = Properties.Settings.Default.PrimaryCurrName;
                //var curr2 = Properties.Settings.Default.SecondryCurrName;
                //DBEPSEntities db = new DBEPSEntities();
                //lb_customer1.Text = db.TB_Customers.Select(x => x.SupplierBalance).ToArray().Sum().ToString() + "   " + curr1;
                //lb_customer2.Text = db.TB_Customers.Select(x => x.SupplierBalanceprim).ToArray().Sum().ToString() + "   " + curr2;

            }
            catch { }
        }


        private void LoadDataSell()
        {
            try
            {
                //currValue = Properties.Settings.Default.CurrConvertValue;
                //var curr1 = Properties.Settings.Default.PrimaryCurrName;
                //var curr2 = Properties.Settings.Default.SecondryCurrName;
                //DBEPSEntities db = new DBEPSEntities();
                //lb_sell1.Text = db.TB_Sell.Select(x => x.SellValue).ToArray().Sum().ToString() + "   " + curr1;
                //double value = (double)((db.TB_Sell.Select(x => x.SellValue).ToArray().Sum()) / currValue);
                //lb_sell2.Text = value.ToString("#0.00") + "   " + curr2;

            }
            catch { }
        }
        private void LoadDataBuy()
        {
            try
            {
                //currValue = Properties.Settings.Default.CurrConvertValue;
                //var curr1 = Properties.Settings.Default.PrimaryCurrName;
                //var curr2 = Properties.Settings.Default.SecondryCurrName;
                //DBEPSEntities db = new DBEPSEntities();
                //lb_buy1.Text = db.TB_Buy.Select(x => x.BuyAllValue).ToArray().Sum().ToString() + "   " + curr1;
                //double value = (double)((db.TB_Buy.Select(x => x.BuyAllValue).ToArray().Sum()) / currValue);
                //lb_buy2.Text = value.ToString("#0.00") + "   " + curr2;

            }
            catch { }
        }


        private void Loadbenfit()
        {
            try
            {
                //currValue = Properties.Settings.Default.CurrConvertValue;
                //var curr1 = Properties.Settings.Default.PrimaryCurrName;
                //var curr2 = Properties.Settings.Default.SecondryCurrName;
                //DBEPSEntities db = new DBEPSEntities();
                //lb_benfit1.Text = db.TB_Buy.Select(x => x.Benfit).ToArray().Sum().ToString() + "   " + curr1;
                //double value = (double)((db.TB_Buy.Select(x => x.Benfit).ToArray().Sum()) / currValue);
                //lb_benfit2.Text = value.ToString("#0.00") + "   " + curr2;

            }
            catch { }
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            LoadData();
        }
    }
}
