using DevExpress.XtraCharts.Native;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Linq;
using System.Runtime.Remoting.Contexts;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.adl;
using THAGBAN_INST.DATA;

namespace THAGBAN_INST.FORM.FRM_LECTUER_MANG.lect_stud
{
    public partial class frm_add_lect_tech : DevExpress.XtraEditors.XtraForm
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        adl.method methods  = new adl.method();
        public int id=0;
        public int stud_id = 0;
        public int cours_id = 0;
        int temp_cours_id = 0;
        public int lect_id = 0;
        int temp_lect_id = 0;
        public string cours_name;
        public string cours_desc;
        public int spaicla_id=0;
        public int tech_id;
        public string spic_year;
        DateTime lect_start;
        DateTime lect_end;


        public frm_add_lect_tech()
        {
            InitializeComponent();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void frm_add_job_Load(object sender, EventArgs e)
        {
           
            if (id != 0)
            {
                try
                {
                    TBL_LECT_TECH_COURS tbl = con.TBL_LECT_TECH_COURS.Find(id);
                    // txt_cours_name.Text = tbl.COURS_NAME.ToString();

                    lect_id = Convert.ToInt32(tbl.LECT_ID);
                    tech_id = Convert.ToInt32(tbl.TECHER_ID);
                    temp_lect_id = lect_id;
                    txt_lect_start.Text = tbl.LECT_START_DATE.ToString();
                    txt_lect_end.Text = tbl.LECT_END_DATE.ToString();
                    txt_group.Text = tbl.GROUP_NAME.ToString();
                    txt_tech_sal.Text = tbl.TECHER_SALARY.ToString();
                    txt_lect_time.Text = tbl.LECT_TIME.ToString();
                    cours_id = Convert.ToInt32(tbl.COURS_ID);
                    temp_cours_id = cours_id;
                   // MessageBox.Show(stud_lect_id.ToString());

                    get_data();
                    //MessageBox.Show(stud_lect_id.ToString());
                }catch(Exception ecx)
                {

                }
            }
            else
            {
                get_data();
            }
           
        }

       void get_group()
        {

            List<string> arr = new List<string>();
            AutoCompleteStringCollection sour = new AutoCompleteStringCollection();
            var tem = (from g in con.TBL_LECT_TECH_COURS.Where(w => w.COURS_ID == cours_id)
                       select
                    new
                    {
                        g.GROUP_NAME,
                    }).Distinct().ToList();
            if (tem != null)
            {
                foreach (var e in tem)
                {
                    sour.Add(e.GROUP_NAME.ToString());

                    // MessageBox.Show(e.GROUP_NAME);
                }
                // sour.AddRange(arr.ToArray());
                txt_group.AutoCompleteCustomSource = sour;


            }
        }
        public void get_data()
        {


            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            
                // Bind data to control when loading complete
                com_tech.DataSource = dbContext.TBL_EMPLOYEES.Join(dbContext.TBL_JOB.
                Where(w => w.JOB_NAME == "مدرس"), s => s.TBL_JOB.JOB_ID, w => w.JOB_ID
                , (tech, job) => new
                {
                    tech.EMP_NAME,
                    tech.EMP_ID,
                }).ToList();
                com_tech.DisplayMember = "EMP_NAME";
                com_tech.ValueMember = "EMP_ID";
            if (id != 0)
            {
                com_tech.SelectedValue = tech_id;
            }

            
            com_lect_cours.DataSource = con.TBL_LECT_COURS.ToList();
            com_lect_cours.DisplayMember = "LECT_COURS_NAME";
            com_lect_cours.ValueMember = "LECT_COURS_ID";
            if (id != 0)
                com_lect_cours.SelectedValue = temp_cours_id;

            //com_cours.DataSource = con.TBL_COURS.ToList();
            //com_cours.DisplayMember = "COURS_NAME";
            //com_cours.ValueMember = "COURS_ID";
            txt_lect_time.Text =DateTime.Now.ToShortTimeString();
           

        }
        void clear()
        {
            spaicla_id =0;
            lect_id = 0;
            id = 0;
            com_lect.Text = "";
            com_lect_cours.Text = "";
            //com_term.Text="";
            //com_year.Text = "";
            cours_id = 0;
            stud_id = 0;
            txt_tech_sal.Text = "";



        }
        bool is_empty()
        {
            if ( com_lect.Text != ""&&txt_group.Text!=""&&txt_tech_sal.Text!="" && com_lect_cours.Text != "" && txt_tech_sal.Text!="")
            {
                return false;
            }
            else
                return true;

        }
        void get_info()
        {


           

            /////
            ///

            
        }
        
        void add_marks()
        {

            tost toast = new tost();
            dialge dialge = new dialge();
            if (is_empty() != true)
            {
                //cheak add or edit 
                try
                {
                    TBL_LECT_TECH_COURS cl = new TBL_LECT_TECH_COURS();
                    cl.COURS_ID = Convert.ToInt32(com_lect_cours.SelectedValue);
                    cl.LECT_ID = Convert.ToInt32(com_lect.SelectedValue);
                    cl.TECHER_ID = Convert.ToInt32(com_tech.SelectedValue.ToString());
                    cl.GROUP_NAME = txt_group.Text;
                    
                    cl.LECT_TIME = txt_lect_time.Text;
                    cl.TECHER_SALARY=Convert.ToInt32(txt_tech_sal.Text);
                    string aa = string.Format("{0:dd-MM-yyyy}", txt_lect_start.Value);
                    lect_start = DateTime.ParseExact(aa, "dd-MM-yyyy", null);
                    cl.LECT_START_DATE = lect_start;
                    string aaa = string.Format("{0:dd-MM-yyyy}", txt_lect_end.Value);
                    lect_end = DateTime.ParseExact(aaa, "dd-MM-yyyy", null);
                    cl.LECT_END_DATE = lect_end;
                    cl.STATE = true;
                    
                    //  cl. =Convert.ToInt32(com_term.SelectedValue.ToString());
                    //cl.YEAR_ID= Convert.ToInt32(com_year.SelectedValue.ToString());
                    //cl.SPEC_ID= Convert.ToInt32(com_spiacl.SelectedValue.ToString());

                    if (id != 0)
                    {
                        //add 
                        cl.TECH_LECT_ID = Convert.ToInt32(id);
                        con.TBL_LECT_TECH_COURS.AddOrUpdate(cl);
                        con.SaveChanges();
                        //toast.Width = this.Width;
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.EditNotificationText, THAGBAN_INST.Properties.Resources.edit_32px);
                        notifiction.Show();

                        clear();
                        //MessageBox.Show("تم التعديل بنجاح ");
                    }
                    else
                    {
                        //update 
                        con.TBL_LECT_TECH_COURS.AddOrUpdate(cl);
                        con.SaveChanges();
                        // toast.Width = this.Width;
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.AddNotificationText, THAGBAN_INST.Properties.Resources.add_32px);
                        notifiction.Show();

                        clear();

                    }
                }
                catch (Exception ex)
                {

                  //  dialge.Width = this.Width;
                    dialge.lbl_mess.Text = ex.Message;
                    dialge.Show();
                }
                clear();
            }
            else
            {
              //  dialge.Width = this.Width;
                dialge.lbl_mess.Text = "الرجاء ادخال جميع البيانات ";
                dialge.Show();



            }


        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            add_marks();
        }

        private void com_spiacl_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if(com_lect_cours.SelectedValue!= null)
            {
                try
                {
                   
                    cours_id = Convert.ToInt32(com_lect_cours.SelectedValue.ToString());
                  var data  = con.TBL_LECTUER.Where(w => w.LECT_COURS_ID == cours_id).ToList();
                    if (data.Count > 0)
                    {
                        com_lect.DataSource = data;
                        com_lect.DisplayMember = "LECT_NAME";
                        com_lect.ValueMember = "LECT_ID";
                        if (lect_id != 0)
                            com_lect.SelectedValue = temp_lect_id;
                    }
                    else
                    {
                       // dialge.lbl_mess.Text = "لايوجد ";
                        //com_year.Items.Clear();
                    }
                    get_group();
                }
                catch(Exception ex)
                {

                }

            }
           
        }

        private void com_year_SelectionChangeCommitted(object sender, EventArgs e)
        {
           
         
        }

        private void ch_year_CheckedChanged(object sender, EventArgs e)
        {
           
        }


        private void com_stud_SelectionChangeCommitted(object sender, EventArgs e)
        {
            
            if (com_tech.SelectedValue != null)
            {
                try
                {
                    tech_id = Convert.ToInt32(com_tech.SelectedValue.ToString());
                }catch(Exception ex)
                {

                }
            }

        }
            //method methods=new method();
            //if(com_tech.SelectedValue!= null)
            //{
            //    try
            //    {
            //        //  List<TBL_STUD_SPEC> tbl = new List<TBL_STUD_SPEC>();
            //        stud_id = Convert.ToInt32(com_tech.SelectedValue.ToString());
            //        // tbl = con.TBL_STUD_SPEC.Where(w=>w.STUD_ID==stud_id).ToList();



            //        var temp1 = con.TBL_SPECIAL.Join(con.TBL_STUD_SPEC.Where(w => w.STUD_ID == stud_id ), sp => sp.SPEC_ID, stud_spe => stud_spe.TBL_SPECIAL.SPEC_ID, (spiec, stud_spic) => new
            //        {
            //            spiec.SPEC_NAME,
            //            spiec.SPEC_ID,

            //        }).ToList();
            //        if (temp1.Count > 0 )
            //        {
            //            com_lect_cours.DataSource = temp1;
            //            com_lect_cours.DisplayMember = "SPEC_NAME";
            //            com_lect_cours.ValueMember = "SPEC_ID";
            //            if (id != 0)
            //            {
                           

            //                com_lect_cours.SelectedValue = lect_id;
            //            }
                       
            //        }
            //        else
            //        {
            //            com_lect_cours.Items.Clear();
            //        }
                   
            //        var temp=con.TBL_COURS.Join(con.TBL_SPE_COURS.Where(w=>w.SPEC_ID==lect_id),
            //            c => c.COURS_ID,
            //            sp=>sp.TBL_COURS.COURS_ID,
            //            (cours,cours_sp)=>
            //             new {
            //                 cours.COURS_ID,
            //                 cours.COURS_NAME,

            //            }).ToList();
            //        if (temp.Count > 0)
            //        {
            //            com_lect.DataSource = temp.ToList();
            //            com_lect.DisplayMember = "COURS_NAME";
            //            com_lect.ValueMember = "COURS_ID";
            //            if (id != 0)
            //                com_lect.SelectedValue = stud_lect_id;
            //        }
            //        else
            //        {
            //            dialge d = new dialge();
            //            com_lect.Items.Clear();
            //            d.lbl_mess.Text = "ولايوجد مواد للتخصص المحدد";

            //            d.Show();

            //        }
            //        // com_cours.SelectedValue = stud_lect_id;

            //    }catch(Exception ex)
            //    {

            //    }

            //}
        

        private void com_term_SelectionChangeCommitted(object sender, EventArgs e)
        {

          

        }

        void get_cours()
        {
            var data = con.TBL_COURS
                       .Join(con.TBL_SPE_COURS.Where(w => w.SPEC_ID == spaicla_id && w.TERM_ID == tech_id
                       && w.YEAR_ID == lect_id),
                       c => c.COURS_ID,
                       spc => spc.TBL_COURS.COURS_ID, (cours, sp_cours) => new
                       {
                           cours.COURS_ID,
                           cours.COURS_NAME,
                       }).ToList();

            if (data.Count > 0)
            {
                com_lect.DataSource = data.ToList();
                com_lect.DisplayMember = "COURS_NAME";
                com_lect.ValueMember = "COURS_ID";
                
                com_lect.SelectedValue = cours_id;
            }
            else
            {
                com_lect.DataSource = null;
                com_lect.Items.Clear();
                dialge d = new dialge();

                d.lbl_mess.Text = "ولايوجد مواد للترم المحدد";

                d.Show();

            }
        }
        private void com_term_SelectedValueChanged(object sender, EventArgs e)
        {
            
        }

        private void com_term_DataSourceChanged(object sender, EventArgs e)
        {
            try
            {
                
              

            }catch(Exception ex) { }
        }

        private void com_cours_SelectedValueChanged(object sender, EventArgs e)
        {
            
        }

        private void com_cours_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (com_lect.SelectedValue != null)
            {
                try
                {
                     cours_id = Convert.ToInt32(com_lect.SelectedValue.ToString());

                }
                catch (Exception ex) { }
            }

        }

        private void txt_group_name_TextChanged(object sender, EventArgs e)
        {

        }
    }
}