using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.job;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.lsits;

namespace THAGBAN_INST.FORM.FRM_EMP_MANEGER.holidays
{
    public partial class frm_add_hloidy : DevExpress.XtraEditors.XtraForm
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int number_day=0;
        public int emp_id = 0;
        public int holiday_id = 0;
        public int holiday_type_id;
        public string holiday_type_name;
        public string emp_name;
        public string note;

        public DateTime holiday_start;
        public DateTime holiday_end;




        public frm_add_hloidy()
        {
            InitializeComponent();
            get_emp();
            get_holid_type();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
         
        }

        public void get_emp()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_EMPLOYEES.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                com_emp_name.DataSource = dbContext.TBL_EMPLOYEES.Where(w => w.STATE == true).ToList() ;
                com_emp_name.DisplayMember = "EMP_NAME";
                com_emp_name.ValueMember = "EMP_ID";
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());


           

        }

        void get_holid_type()
        {
            db_max_instEntities dbContext = new db_max_instEntities();

            dbContext.TBL_HOLIDAY_TYPE.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                com_holiday_type.DataSource = dbContext.TBL_HOLIDAY_TYPE.Local.ToBindingList();
                com_holiday_type.DisplayMember = "HOLIDAY_TYPE_NAME";
                com_holiday_type.ValueMember = "HOLIDAY_TYPE_ID";
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

        }




        void clear()
        {
            holiday_type_id =0;
            emp_id = 0;
            txt_note.Text = "";
            txt_n_day.Text = "";
           
            txt_hliday_start.Value = DateTime.Now;
            txt_hliday_end.Value = DateTime.Now;
            com_emp_name.Text = "";
            com_holiday_type.Text = "";
          




        }
        bool is_empty()
        {
            if (com_emp_name.Text != "" && com_holiday_type.Text!="" && txt_n_day.Text!="")
            {
                number_day = Convert.ToInt32(txt_n_day.Text);
                string aa = string.Format("{0:dd-MM-yyyy}", txt_hliday_start.Value);
                holiday_start= DateTime.ParseExact(aa, "dd-MM-yyyy", null);
                string a = string.Format("{0:dd-MM-yyyy}", txt_hliday_end.Value);
                holiday_end = DateTime.ParseExact(a, "dd-MM-yyyy", null);


                return false;
            }
            else
                return true;

        }

        void add_holiday()
        {

            tost toast = new tost();
            dialge dialge = new dialge();
            if (is_empty() != true)
            {
                //cheak add or edit 
                try
                {
                    TBL_HOLIDAYS cl = new TBL_HOLIDAYS();

                    cl.EMP_ID = emp_id;
                    cl.HOLIDAY_TYPE_ID = holiday_type_id;
                    cl.HOLIDAY_START = holiday_start;
                    cl.HOLIDAY_END = holiday_end;
                    cl.HOLIDAY_N_DAY = number_day;
                    cl.NOTE = txt_note.Text;
                    if (holiday_id != 0)
                    {
                        //add 
                        cl.HOLIDAY_ID = Convert.ToInt32(holiday_id);
                        con.TBL_HOLIDAYS.AddOrUpdate(cl);
                        con.SaveChanges();

                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.EditNotificationText, THAGBAN_INST.Properties.Resources.edit_32px);
                        notifiction.Show();
                        clear();
                        //MessageBox.Show("تم التعديل بنجاح ");
                    }
                    else
                    {
                        //update 
                        con.TBL_HOLIDAYS.AddOrUpdate(cl);
                        con.SaveChanges();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.AddNotificationText, THAGBAN_INST.Properties.Resources.add_32px);
                        notifiction.Show();
                        clear();

                    }
                }
                catch (Exception ex)
                {


                    //dialge.Width = this.Width;
                    //dialge.lbl_mess.Text ="تاكد من ادخال البيانات بالشكل الصحيح ";
                    //dialge.Show();
                    MessageBox.Show(ex.Message + ex.InnerException.ToString());
                }
              
            }
            else
            {
                dialge.Width = this.Width;
                dialge.lbl_mess.Text = "الرجاء ادخال جميع البيانات ";
                dialge.Show();



            }


        }

        void cheack()
        {
            try
            {
                number_day = Convert.ToInt32(txt_n_day.Text);

            }
            catch (Exception ex)
            {

            }
            dialge dialge = new dialge();
           
                txt_hliday_end.Value = txt_hliday_start.Value.AddDays(number_day);

                
           
            
            
                //if (txt_hliday_start.Value > txt_hliday_end.Value)
                //{
                //    dialge.lbl_mess.Text= "تاريخ بدايه الاجازه اكبر من تاريخ انتهائها ";
                //    dialge.Show();
                //}
                //else
                //{
                //    number_day = txt_hliday_end.Value.Day - txt_hliday_start.Value.Day;  
                //}

            
        }
        private void frm_add_emp_Load(object sender, EventArgs e)
        {

           get_emp();
            cheack();

            if (emp_id != 0)
            {
                txt_hliday_start.Value = holiday_start;
                com_emp_name.Text = emp_name;
                com_holiday_type.Text = holiday_type_name;
                txt_n_day.Text = number_day.ToString();
                txt_note.Text = note;
                txt_hliday_end.Value = holiday_end;
                //holiday_type_id = Convert.ToInt32(com_holiday_type.SelectedValue.ToString());
                //stud_id= Convert.ToInt32(com_emp_name.SelectedValue.ToString());
                label1.Text = "emp=" + emp_id.ToString() + "hold" + holiday_type_id.ToString();


            }

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {

            clear();
          

        }

        private void com_dept_SelectedIndexChanged(object sender, EventArgs e)
        {
            
        }

        private void com_dept_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (com_holiday_type.SelectedItem != null)
            {
                holiday_type_id = Convert.ToInt32(com_holiday_type.SelectedValue.ToString());
            }
         
        }

        private void lbl_dept_Click(object sender, EventArgs e)
        {
            FRM_ADD_DEP frm = new FRM_ADD_DEP();
            frm.ShowDialog();
        }

        private void labelControl9_Click(object sender, EventArgs e)
        {
            frm_add_job frm = new frm_add_job();
            frm.ShowDialog(this);

        }

        private void btn_list_dept_Click(object sender, EventArgs e)
        {
           
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
         
        }

        private void ch_mal_CheckedChanged(object sender, EventArgs e)
        {
            //if (ch_mal.Checked == true)
            //{

            //    ch_fmel.Checked = false;
            //    stud_gender = "ذكر";
            //}
            //else
            //    ch_fmel.Checked = true;
          


        }

        private void ch_fmel_CheckedChanged(object sender, EventArgs e)
        {
          
            cheack();


    }

    private void btn_save_Click(object sender, EventArgs e)
        {
            add_holiday();

        }

        private void com_job_SelectionChangeCommitted(object sender, EventArgs e)
        {
           
        }

        private void btn_emp_list_Click(object sender, EventArgs e)
        {
            emp_list frm = new emp_list();
            frm.ShowDialog(this);
            emp_id = frm.emp_id;
            com_emp_name.Text = frm.emp_name;
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            emp_list frm = new emp_list();
            frm.ShowDialog(this);
            emp_id = frm.emp_id;
            com_emp_name.Text = frm.emp_name;
        }

        private void simpleButton3_Click_1(object sender, EventArgs e)
        {
            holiday_type_list frm = new holiday_type_list();
            frm.ShowDialog(this);
            holiday_type_id = frm.holiday_type_id;
            holiday_type_name=frm.holiday_type_name;
            com_holiday_type.Text = frm.holiday_type_name;
        }

        private void txt_n_day_TextChanged(object sender, EventArgs e)
        {
            cheack();
        }

        private void txt_hliday_start_ValueChanged(object sender, EventArgs e)
        {
            // txt_n_day.Text = (txt_hliday_end.Value.Day - txt_hliday_start.Value.Day).ToString();
            get_n_day();
        }
        void get_n_day()
        {

            //var numberOfDays = (end - statrt).TotalDays;
            TimeSpan x = txt_hliday_end.Value - txt_hliday_start.Value;
            txt_n_day.Text = x.Days.ToString();

        }
            

        private void txt_hliday_end_ValueChanged(object sender, EventArgs e)
        {
            get_n_day();

        }

        private void com_emp_name_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (com_emp_name.SelectedItem != null)
            {
                emp_id = Convert.ToInt32(com_emp_name.SelectedValue);
            }
        }
    }
}