using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.DATA;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.job;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.lsits;

namespace THAGBAN_INST.FORM.FRM_EMP_MANEGER.holidays
{
    public partial class frm_mang_holiday : DevExpress.XtraEditors.XtraUserControl
    {
       db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        //public int tech_id;

        //public string matrial_name;
        //public string stud_lect_id;
        //public string spical_price;
        //public string spiacla_id;
        //public string cours_name;
        //public bool spical_state;
        //public DateTime spical_date;
        public int number_day = 0;
        public int emp_id = 0;
        public int holiday_id = 0;
        public int holiday_type_id;
        public string holiday_type_name;
        public string emp_name;
        public string note;

        public DateTime holiday_start;
        public DateTime holiday_end;
        public frm_mang_holiday()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_HOLIDAYS.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_HOLIDAYS.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
           
        }
        void get_data()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_HOLIDAYS.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_HOLIDAYS.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridView2_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
            get_sel();
        }
        void get_sel()
        {
            if (gridView2.SelectedRowsCount > 0)
            {
                try
                {
                    holiday_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("HOLIDAY_ID").ToString());
                    emp_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("EMP_ID").ToString());
                    holiday_type_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("HOLIDAY_TYPE_ID").ToString());
                    holiday_start = Convert.ToDateTime(gridView2.GetFocusedRowCellValue("HOLIDAY_START").ToString());
                    holiday_end = Convert.ToDateTime(gridView2.GetFocusedRowCellValue("HOLIDAY_END").ToString());
                    number_day = Convert.ToInt32(gridView2.GetFocusedRowCellValue("HOLIDAY_N_DAY").ToString());
                    note = gridView2.GetFocusedRowCellValue("NOTE").ToString();

                    emp_name = con.TBL_EMPLOYEES.Find(emp_id).EMP_NAME;
                    holiday_type_name = con.TBL_HOLIDAY_TYPE.Find(holiday_type_id).HOLIDAY_TYPE_NAME;

                }catch (Exception ex)
                {

                }
            }
        }

        private void btn_edite_Click(object sender, EventArgs e)
        {
            frm_add_hloidy frm = new frm_add_hloidy();
            get_sel();
            frm.holiday_id = holiday_id;
            frm.emp_id = emp_id;
            frm.holiday_start=holiday_start;
            frm.holiday_type_id=holiday_type_id;
            frm.holiday_type_name = holiday_type_name;
            frm.number_day = number_day;
            frm.holiday_end=holiday_end;
            frm.emp_name=emp_name;
            frm.note=note;
            frm.btn_save.Text = "تعديل";
            frm.ShowDialog();
            get_data();
        }

        private void btn_save_Click(object sender, EventArgs e)
        {
            frm_add_hloidy frm = new frm_add_hloidy();
            frm.holiday_id = 0;
            frm.ShowDialog();
            get_data();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
        }
        void delete()
        {
            if (holiday_id != 0)
            {
                try
                {
                    DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    if (res == DialogResult.OK)
                    {
                        TBL_HOLIDAYS del_cle = con.TBL_HOLIDAYS.Find(holiday_id);
                        // del_doc.DOC_ID = holiday_type_id;

                        con.TBL_HOLIDAYS.Remove(del_cle);
                        con.SaveChanges();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.DeleteNotificationText, THAGBAN_INST.Properties.Resources.Delete_32px);
                        notifiction.Show();
                    }
                    get_data();
                }catch (Exception ex) { }
            }
        }

        private void gridView2_SelectionChanged_1(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
            get_sel();

        }
    }
}
