using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using THAGBAN_INST.DATA;
using DevExpress.XtraCharts.Native;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Button;

namespace THAGBAN_INST.FORM.FRM_LECTUER_MANG
{
    public partial class analys_admin : DevExpress.XtraEditors.XtraUserControl
    {
        private int lect_id;
        db_max_instEntities con = new db_max_instEntities();
        private int tech_lect_id;
        string courne1 = THAGBAN_INST.Properties.Settings.Default.courncy;
        public analys_admin()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard

            load_good_pad();
            // load_send_rest();
            cheack_change();
            Get_piad();
            get_seles();



         
            THAGBAN_INST.DATA.db_max_instEntities dbContext = new THAGBAN_INST.DATA.db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_STUD_LECT.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                chartControl1.DataSource = dbContext.TBL_STUD_LECT.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        void get_data()
        {
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.

            // Bind data to control when loading complete
            chartControl1.DataSource = con.TBL_STUD_LECT.ToList();
        }
        private void load_good_pad()
        {
            try
            {
                
                db_max_instEntities db = new db_max_instEntities();
                lbl_good1.Text = db.TBL_LECT_MARK.GroupBy(
                    grp => new {grp.STUD_ID,grp.TBL_LECT_TECH_COURS.GROUP_NAME,grp.TBL_LECTUER.LECT_NAME}
                    ).Where(
                    x => x.Min(w=>w.MARK_VALUE)>=50).Count().ToString() + "   ";
                lbl_pad1.Text = db.TBL_LECT_MARK.GroupBy(
                    grp => new { grp.STUD_ID, grp.TBL_LECT_TECH_COURS.GROUP_NAME, grp.TBL_LECTUER.LECT_NAME }
                    ).Where(
                    x => x.Min(w => w.MARK_VALUE) <50).Count().ToString() + "   ";
               // value.ToString("#0.00") + "   " + curr2;

            }
            catch { }
        }

        private void load_send_rest()
        {
            try
            {

                db_max_instEntities db = new db_max_instEntities();
                lbl_rest2.Text = db.TBL_SEND_STUD_LECT.GroupBy(
                   
                        grp => new
                        {
                            grp.STUD_ID,
                            grp.TECH_LECT_ID,
                            grp.LECT_ID,
                        }
                    ).Where(
                    x => x.Sum(w=>w.PAID_UP) < Convert.ToInt32(x.Select(w => w.TBL_LECTUER.LECT_PRICE).ToString()))
                    .Select( x => Convert.ToInt32(x.Select(w => w.TBL_LECTUER.LECT_PRICE).ToString())
                    - x.Sum(s => s.PAID_UP) )
                
                    .ToString() + "ريال  ";
               
                lbl_rest1.Text = db.TBL_SEND_STUD_LECT.GroupBy(
                    grp => new {
                        grp.STUD_ID,
                        grp.TECH_LECT_ID,
                        grp.LECT_ID,

                    }
                    ).Where(
                    x => x.Sum(s => s.PAID_UP)<Convert.ToInt32(x.Select(w=>w.TBL_LECTUER.LECT_PRICE).ToString()))
              .Count() .ToString() + "   ";
                // value.ToString("#0.00") + "   " + curr2;

            }
            catch { }
        }

        void Get_piad()
        {

            try
            {


                int piad_count = 0;
                long total_rest = 0;
                if (ch_lect.Checked == true && ch_grou.Checked == false)
                {
                    if (com_lect.SelectedValue != null)
                        lect_id = Convert.ToInt32(com_lect.SelectedValue);
                    var result = con.TBL_SEND_STUD_LECT
        .GroupBy(cGrp => new { cGrp.TECH_LECT_ID, cGrp.LECT_ID, cGrp.STUD_ID })
        .Select(g => new { Name = g, Guns = g.Sum(x => x.PAID_UP) })
        .ToList();


                    foreach (var g in result.Where(w => w.Name.Key.LECT_ID == lect_id).ToList())
                    {
                        if (g.Guns < Convert.ToInt32(con.TBL_LECTUER.Find(g.Name.Key.LECT_ID).LECT_PRICE))
                        {
                            piad_count++;
                            total_rest += (long)(Convert.ToInt32(con.TBL_LECTUER.Find(g.Name.Key.LECT_ID).LECT_PRICE) - g.Guns);

                        }
                    }
                   
                }
                else if (ch_lect.Checked == true && ch_grou.Checked == true)
                {
                    if (com_lect.SelectedValue != null)
                        tech_lect_id = Convert.ToInt32(com_group.SelectedValue);
                    var result = con.TBL_SEND_STUD_LECT
        .GroupBy(cGrp => new { cGrp.TECH_LECT_ID, cGrp.LECT_ID, cGrp.STUD_ID })
        .Select(g => new { Name = g, Guns = g.Sum(x => x.PAID_UP) })
        .ToList();


                    foreach (var g in result.Where(w => w.Name.Key.LECT_ID == lect_id && w.Name.Key.TECH_LECT_ID == tech_lect_id).ToList())
                    {
                        if (g.Guns < Convert.ToInt32(con.TBL_LECTUER.Find(g.Name.Key.LECT_ID).LECT_PRICE))
                        {
                            piad_count++;
                            total_rest += (long)(Convert.ToInt32(con.TBL_LECTUER.Find(g.Name.Key.LECT_ID).LECT_PRICE) - g.Guns);

                        }
                    }
                }

                else
                {
                    var result = con.TBL_SEND_STUD_LECT
        .GroupBy(cGrp => new { cGrp.TECH_LECT_ID, cGrp.LECT_ID, cGrp.STUD_ID })
        .Select(g => new { Name = g, Guns = g.Sum(x => x.PAID_UP) })
        .ToList();


                    foreach (var g in result)
                    {
                        if (g.Guns < Convert.ToInt32(con.TBL_LECTUER.Find(g.Name.Key.LECT_ID).LECT_PRICE))
                        {
                            piad_count++;
                        total_rest +=(long)(Convert.ToInt32(con.TBL_LECTUER.Find(g.Name.Key.LECT_ID).LECT_PRICE) - g.Guns);


                        }
                    }

                }

                lbl_rest1.Text = piad_count.ToString();
                lbl_rest2.Text = total_rest.ToString()+" "+ courne1;

            }
            catch (Exception ex) { }

        }

        void get_seles()
        {
            try
            {
                lb_benfit1.Text = con.TBL_OPRATION.Where(w => w.OPRATION_TYPE.Equals("سحب")).Sum(w => w.PORATION_AMOUNT).ToString();
                lb_sell1.Text = con.TBL_OPRATION.Where(w => w.OPRATION_TYPE.Equals("ايداع")).Sum(w => w.PORATION_AMOUNT).ToString();
                int inst_id = THAGBAN_INST.Properties.Settings.Default.inst_id;
                lb_buy1.Text = con.TBL_INST.Find(inst_id).INST_TOTAL.ToString();
                lb_benfit2.Text = " " + courne1;
                lb_buy2.Text = " " + courne1;
                lb_sell2.Text = " " + courne1;
            }catch (Exception ex)
            {

            }

        }
        public void get_lect()
        {
            var tbl = con.TBL_LECT_TECH_COURS.Where(w => w.STATE == true)
                .Join(con.TBL_LECTUER, l => l.TBL_LECTUER.LECT_ID, tl => tl.LECT_ID,
                (l, tl) => new
                {

                    l.LECT_ID,

                    tl.LECT_NAME,

                }).Distinct();


            if (tbl != null)
            {
                com_lect.DataSource = tbl.ToList();
                com_lect.DisplayMember = "LECT_NAME";
                com_lect.ValueMember = "LECT_ID";
                get_group();


            }
            else
            {
                com_lect.DataSource = null;
                com_lect.Items.Clear();
                com_lect.Text = "";
            }
        }
        public void get_group()
        {
            try
            {

                lect_id = Convert.ToInt32(com_lect.SelectedValue);
                var temp = con.TBL_LECT_TECH_COURS.Where(w => w.LECT_ID == lect_id).Distinct().ToList();
                if (temp != null)
                {
                    com_group.DataSource = temp;
                    com_group.DisplayMember = "GROUP_NAME";
                    com_group.ValueMember = "TECH_LECT_ID";


                }
                else
                {
                    com_group.DataSource = null;
                    com_group.Items.Clear();
                    com_group.Text = "";
                }
            }
            catch (Exception ex) { }


        }
        void cheack_change()
        {

            if (ch_lect.Checked)
            {
                com_lect.Enabled = true;
            }
            else
            {
                com_lect.Enabled = false;
            }
            if (ch_grou.Checked)
            {
                com_group.Enabled = true;

            }
            else
            {
                //groupBox1.Enabled = false;
                //groupBox1.Visible = false;
                com_group.Enabled = false;
            }
           
            Get_piad();
        }

        private void label4_Click(object sender, EventArgs e)
        {

        }

        private void flowLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            load_good_pad();
           // load_send_rest();
            Get_piad();
            get_seles();
            get_data();
            load_good_pad();

        }

        private void com_lect_SelectedIndexChanged(object sender, EventArgs e)
        {
            get_group();
            Get_piad();
        }

        private void com_group_SelectedIndexChanged(object sender, EventArgs e)
        {
           // get_group();
            Get_piad();
        }

        private void ch_lect_CheckedChanged(object sender, EventArgs e)
        {
            cheack_change();
            get_lect();
            Get_piad();
        }

        private void ch_grou_CheckedChanged(object sender, EventArgs e)
        {
            cheack_change();
            get_group();
            Get_piad();
            get_seles();
        }
    }
}
