using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using THAGBAN_INST.adl;
using THAGBAN_INST.DATA;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.job;
using THAGBAN_INST.FORM.FRM_EMP_MANEGER.lsits;

namespace THAGBAN_INST.FORM.FRM_EMP_MANEGER.attends
{
    public partial class add_attends : DevExpress.XtraEditors.XtraForm
    {

        db_max_instEntities con = new db_max_instEntities();
        tost toast = new tost();
        dialge dialge = new dialge();
        public int emp_id = 0;
        public string emp_name;
        public string note;

        public int GET_EMP;
        public int attend_id;
        public int GO_EMP;
        public DateTime attend_date;





        public add_attends()
        {
            InitializeComponent();
            get_emp();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
         
        }

        public void get_emp()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            db_max_instEntities dbContext = new db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_EMPLOYEES.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                com_emp_name.DataSource = dbContext.TBL_EMPLOYEES.Where(w=>w.STATE==true).ToList();
                com_emp_name.DisplayMember = "EMP_NAME";
                com_emp_name.ValueMember = "EMP_ID";
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());


            // get holidat type 
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            

        }

       




        void clear()
        {
            emp_id = 0;
           
           
            txt_get_emp.Value =0;
            txt_go_emp.Value = 0;
            txt_attends_date.Value = DateTime.Now;
            com_emp_name.Text = "";
           
          




        }
        bool is_empty()
        {
            if (com_emp_name.Text != "" &&txt_get_emp.Value!=0 && txt_go_emp.Value!=0 )
            {
                string aa = string.Format("{0:dd-MM-yyyy}", txt_attends_date.Value);
                attend_date= DateTime.ParseExact(aa, "dd-MM-yyyy", null);
                GO_EMP =Convert.ToInt32(txt_go_emp.Value);
                GET_EMP = Convert.ToInt32(txt_get_emp.Value);
               


                return false;
            }
            else
                return true;

        }

        void add_attend()
        {

            tost toast = new tost();
            dialge dialge = new dialge();
            if (is_empty() != true)
            {
                //cheak add or edit 
                try
                {
                    TBL_ATTENDS cl = new TBL_ATTENDS();

                    cl.EMP_ID = emp_id;
                    cl.ATTEND_GO = GO_EMP;
                    cl.ATTEND_GIT = GET_EMP;

                    cl.ATTEND_DATE = attend_date;
                    if (attend_id != 0)
                    {
                        //add 
                        cl.ATTEND_ID = Convert.ToInt32(attend_id);
                        con.TBL_ATTENDS.AddOrUpdate(cl);
                        con.SaveChanges();

                        adl.NotifictionUser notifiction = new adl.NotifictionUser("تم اخذ الحظور بنجاح ", THAGBAN_INST.Properties.Resources.add_32px);
                        notifiction.Show();
                        clear();
                        //MessageBox.Show("تم التعديل بنجاح ");
                    }
                    else
                    {
                        //update 
                        con.TBL_ATTENDS.AddOrUpdate(cl);
                        con.SaveChanges();
                        NotifictionUser notifiction = new NotifictionUser(THAGBAN_INST.Properties.Resources.AddNotificationText, THAGBAN_INST.Properties.Resources.add_32px);

                        notifiction.Show();
                        clear();

                    }
                }
                catch (Exception ex)
                {


                    dialge.Width = this.Width;
                    dialge.lbl_mess.Text = "تاكد من ادخال البيانات بالشكل الصحيح ";
                    dialge.Show();
                    //  MessageBox.Show(ex.Message + ex.InnerException.ToString());
                }
              
            }
            else
            {
                dialge.Width = this.Width;
                dialge.lbl_mess.Text = "الرجاء ادخال جميع البيانات ";
                dialge.Show();



            }


        }

        
        private void frm_add_emp_Load(object sender, EventArgs e)
        {

           get_emp();

            if (attend_id != 0)
            {
                txt_attends_date.Value = attend_date;
                com_emp_name.Text = emp_name;
                txt_get_emp.Text = GET_EMP.ToString();
                txt_go_emp.Text = GO_EMP.ToString();
                //holiday_type_id = Convert.ToInt32(com_holiday_type.SelectedValue.ToString());
                //stud_id= Convert.ToInt32(com_emp_name.SelectedValue.ToString());
                label1.Text = "emp=" + emp_id.ToString() + "hold" + attend_id.ToString();


            }

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {

            clear();
          

        }

    

    private void btn_save_Click(object sender, EventArgs e)
        {
            add_attend();

        }

       

        private void btn_emp_list_Click(object sender, EventArgs e)
        {
            emp_list frm = new emp_list();
            frm.ShowDialog(this);
            emp_id = frm.emp_id;
            com_emp_name.Text = frm.emp_name;
        }

       
        
        
       
       

        
        private void com_emp_name_SelectionChangeCommitted(object sender, EventArgs e)
        {
            if (com_emp_name.SelectedItem != null)
            {
                emp_id = Convert.ToInt32(com_emp_name.SelectedValue);
            }
        }

        

        private void simpleButton1_Click_1(object sender, EventArgs e)
        {
            clear();
        }
    }
}